---
sidebar: sidebar 
permalink: trident-docker/known-issues-docker.html 
keywords: known issues, trident, trident for docker, docker 
summary: 'Recherchez des informations sur les problèmes connus lors de l"utilisation de Trident avec Docker.' 
---
= Problèmes et limites connus
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trouvez des informations sur les problèmes connus et les limites lors de l'utilisation de Trident avec Docker.



[[upgrading-trident-docker-volume-plugin-to-20-10-and-later-from-older-versions-results-in-upgrade-failure-with-the-no-such-file-or-directory-error]]
== La mise à niveau de Trident Docker Volume Plug-in vers la version 20.10 et ultérieure à partir des versions plus anciennes entraîne un échec de mise à niveau, sans erreur de fichier ou de répertoire de ce type.

.Solution de contournement
. Désactivez le plug-in.
+
[source, console]
----
docker plugin disable -f netapp:latest
----
. Retirez le plug-in.
+
[source, console]
----
docker plugin rm -f netapp:latest
----
. Réinstallez le plug-in en fournissant le complément `config` paramètre.
+
[source, console]
----
docker plugin install netapp/trident-plugin:20.10 --alias netapp --grant-all-permissions config=config.json
----




[[volume-names-must-be-a-minimum-of-2-characters-in-length]]
== Les noms de volumes doivent comporter au moins 2 caractères.


NOTE: Il s'agit d'une limitation client Docker. Le client interprète un seul nom de caractère comme étant un chemin Windows. https://github.com/moby/moby/issues/25773["Voir bug 25773"^].



[[docker-swarm-has-certain-behaviors-that-prevent-trident-from-supporting-it-with-every-storage-and-driver-combination]]
== Docker Swarm présente certains comportements qui empêchent Trident de le prendre en charge avec toutes les combinaisons de stockage et de pilotes.

* Docker Swarm utilise actuellement le nom du volume, mais pas l'ID de volume, comme identifiant de volume unique.
* Les requêtes de volume sont envoyées simultanément à chaque nœud d'un cluster Swarm.
* Les plug-ins de volume (y compris Trident) doivent s'exécuter indépendamment sur chaque nœud d'un cluster Swarm. En raison du fonctionnement de ONTAP et du `ontap-nas` fonctionnement des pilotes et `ontap-san`, ce sont eux qui sont les seuls à pouvoir fonctionner dans ces limites.


Les autres pilotes sont soumis à des problèmes tels que les conditions de course qui peuvent entraîner la création d'un grand nombre de volumes pour une seule demande sans « gagnant » clair ; par exemple, Element dispose d'une fonctionnalité qui permet aux volumes d'avoir le même nom mais des ID différents.

NetApp a fourni des commentaires à l'équipe Docker, mais ne fournit aucune indication de recours futur.



[[if-a-flexgroup-is-being-provisioned-ontap-does-not-provision-a-second-flexgroup-if-the-second-flexgroup-has-one-or-more-aggregates-in-common-with-the-flexgroup-being-provisioned]]
== Si un FlexGroup est provisionné, ONTAP ne provisionne pas un deuxième FlexGroup si le deuxième FlexGroup dispose d'un ou de plusieurs agrégats en commun avec la FlexGroup provisionnée.
