---
sidebar: sidebar 
permalink: trident-docker/stor-config.html 
keywords: deploy, trident, docker, trident for docker, nfs, iscsi, protocol, nfs protocol, iscsi protocol, configure host, host config, storage config, options, variables, ontap, element, storage pool, cvs, cvs-performance, service type, service level, cloud volumes service, cloud volumes 
summary: Consultez les options de configuration disponibles pour vos configurations Trident. 
---
= Options de configuration du stockage
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Consultez les options de configuration disponibles pour vos configurations Trident.



== Options de configuration globale

Ces options de configuration s'appliquent à toutes les configurations Trident, quelle que soit la plateforme de stockage utilisée.

[cols="3*"]
|===
| Option | Description | Exemple 


| `version`  a| 
Numéro de version du fichier de configuration
 a| 
`1`



| `storageDriverName`  a| 
Nom du pilote de stockage
 a| 
`ontap-nas`, `ontap-san`, `ontap-nas-economy`,
`ontap-nas-flexgroup`, `solidfire-san`



| `storagePrefix`  a| 
Préfixe facultatif pour les noms de volumes. Valeur par défaut : `netappdvp_`.
 a| 
`staging_`



| `limitVolumeSize`  a| 
Restriction facultative sur les tailles de volume. Par défaut : « » (non appliqué)
 a| 
`10g`

|===

TIP: N'utilisez pas `storagePrefix` (y compris la valeur par défaut) les systèmes back-end Element. Par défaut, le `solidfire-san` pilote ignore ce paramètre et n'utilise pas de préfixe. NetApp recommande d'utiliser soit un tenantID spécifique pour le mappage de volume Docker, soit des données d'attribut renseignées sur la version Docker, les informations sur le pilote et le nom brut de Docker au cas où un nom munging aurait pu être utilisé.

Les options par défaut sont disponibles pour éviter d'avoir à les spécifier sur chaque volume que vous créez. Le `size` option disponible pour tous les types de contrôleurs. Pour un exemple de définition de la taille de volume par défaut, reportez-vous à la section ONTAP configuration.

[cols="3*"]
|===
| Option | Description | Exemple 


| `size`  a| 
Taille par défaut facultative pour les nouveaux volumes. Valeur par défaut : `1G`
 a| 
`10G`

|===


== Configuration ONTAP

Outre les valeurs de configuration globale ci-dessus, lorsque vous utilisez ONTAP, les options de premier niveau suivantes sont disponibles.

[cols="3*"]
|===
| Option | Description | Exemple 


| `managementLIF`  a| 
Adresse IP de la LIF de management ONTAP. Vous pouvez spécifier un nom de domaine complet (FQDN).
 a| 
`10.0.0.1`



| `dataLIF`  a| 
Adresse IP de la LIF de protocole.

*Pilotes NAS ONTAP*: NetApp recommande de spécifier `dataLIF`. Si non fourni, Trident récupère les LIFs de données du SVM. Vous pouvez spécifier un nom de domaine complet (FQDN) à utiliser pour les opérations de montage NFS, ce qui vous permet de créer un DNS circulaire pour équilibrer la charge sur plusieurs dataLIFs.

*Pilotes SAN ONTAP* : ne spécifiez pas pour iSCSI ou FC. Trident utilise link:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["Mappage de LUN sélectif ONTAP"^] pour détecter les LIF iSCSI ou FC requises pour établir une session à chemins multiples. Un avertissement est généré si `dataLIF` est explicitement défini.
 a| 
`10.0.0.2`



| `svm`  a| 
Storage Virtual machine à utiliser (requis, si la LIF de gestion est une LIF de cluster)
 a| 
`svm_nfs`



| `username`  a| 
Nom d'utilisateur pour la connexion au périphérique de stockage
 a| 
`vsadmin`



| `password`  a| 
Mot de passe pour se connecter au périphérique de stockage
 a| 
`secret`



| `aggregate`  a| 
Agrégat pour le provisionnement (facultatif ; si défini, doit être attribué au SVM) Pour le `ontap-nas-flexgroup` pilote, cette option est ignorée. Tous les agrégats affectés au SVM sont utilisés pour provisionner un volume FlexGroup.
 a| 
`aggr1`



| `limitAggregateUsage`  a| 
Facultatif, le provisionnement échoue si l'utilisation est supérieure à ce pourcentage
 a| 
`75%`



| `nfsMountOptions`  a| 
Contrôle granulaire des options de montage NFS ; par défaut : «-o nfssvers=3 ». *Disponible uniquement pour le `ontap-nas` et `ontap-nas-economy` pilotes*. https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["Pour plus d'informations sur la configuration de l'hôte NFS, consultez ici"^].
 a| 
`-o nfsvers=4`



| `igroupName`  a| 
Trident crée et gère par nœud `igroups` en tant que `netappdvp`.

Cette valeur ne peut pas être modifiée ou omise.

*Disponible uniquement pour le `ontap-san` pilote*.
 a| 
`netappdvp`



| `limitVolumeSize`  a| 
Taille maximale du volume éligible.
 a| 
`300g`



| `qtreesPerFlexvol`  a| 
Le nombre maximal de qtrees par FlexVol doit être compris dans la plage [50, 300], la valeur par défaut est 200.

*Pour le `ontap-nas-economy` Pilote, cette option permet de personnaliser le nombre maximal de qtrees par FlexVol*.
 a| 
`300`



 a| 
`sanType`
| *Pris en charge pour le `ontap-san` pilote uniquement.* Utilisez pour sélectionner `iscsi` pour iSCSI, `nvme` pour NVMe/TCP ou `fcp` pour SCSI over Fibre Channel (FC). | `iscsi` si vide 


| `limitVolumePoolSize` | *Pris en charge pour `ontap-san-economy` les `ontap-san-economy` pilotes et uniquement.* Limite la taille des FlexVol pour les modèles économiques ONTAP ONTAP-nas et ONTAP-SAN.  a| 
`300g`

|===
Les options par défaut sont disponibles pour éviter d'avoir à les spécifier sur chaque volume que vous créez :

[cols="1,3,2"]
|===
| Option | Description | Exemple 


| `spaceReserve`  a| 
Mode de réservation d'espace ; `none` (provisionnement fin) ou `volume` (épais)
 a| 
`none`



| `snapshotPolicy`  a| 
Règle Snapshot à utiliser ; la valeur par défaut est `none`
 a| 
`none`



| `snapshotReserve`  a| 
Pourcentage de réserve de snapshot. La valeur par défaut est « » pour accepter la valeur par défaut de ONTAP
 a| 
`10`



| `splitOnClone`  a| 
Séparer un clone de son parent lors de sa création. Par défaut, la valeur est `false`
 a| 
`false`



| `encryption`  a| 
Active NetApp Volume Encryption (NVE) sur le nouveau volume ; valeur par défaut sur `false`. Pour utiliser cette option, NVE doit être sous licence et activé sur le cluster.

Si NAE est activé sur le back-end, tout volume provisionné dans Trident est activé.

Pour plus d'informations, reportez-vous à la section : link:../trident-reco/security-reco.html["Fonctionnement de Trident avec NVE et NAE"].
 a| 
vrai



| `unixPermissions`  a| 
L'option NAS pour les volumes NFS provisionnés est définie par défaut sur `777`
 a| 
`777`



| `snapshotDir`  a| 
Option NAS pour accéder au `.snapshot` répertoire.
 a| 
« True » pour NFSv4 « false » pour NFSv3



| `exportPolicy`  a| 
L'option NAS pour la export policy NFS à utiliser est définie par défaut sur `default`
 a| 
`default`



| `securityStyle`  a| 
Option NAS pour l'accès au volume NFS provisionné.

Prise en charge de NFS `mixed` et `unix` styles de sécurité. La valeur par défaut est `unix`.
 a| 
`unix`



| `fileSystemType`  a| 
OPTION SAN pour sélectionner le type de système de fichiers, par défaut sur `ext4`
 a| 
`xfs`



| `tieringPolicy`  a| 
Règle de hiérarchisation à utiliser, la valeur par défaut est `none`.
 a| 
`none`

|===


=== Options d'évolutivité

Les `ontap-nas` pilotes et `ontap-san` créent un ONTAP FlexVol pour chaque volume Docker. ONTAP prend en charge jusqu'à 1000 volumes FlexVol par nœud de cluster avec un maximum de 12,000 volumes FlexVol si vos exigences de volume Docker correspondent à cette limitation, le `ontap-nas` pilote est la solution NAS préférée en raison des fonctionnalités supplémentaires proposées par FlexVols, telles que les copies Snapshot granulaires de volume Docker et le clonage.

Si vous avez besoin de plus de volumes Docker que ne peut pas être pris en charge par les limites FlexVol, choisissez la `ontap-nas-economy` ou le `ontap-san-economy` conducteur.

Le `ontap-nas-economy` pilote crée des volumes Docker en tant que qtrees ONTAP au sein d'un pool de qtrees de volumes FlexVol automatiquement gérés pour une évolutivité bien supérieure, jusqu'à 100,000 par nœud de cluster et 2,400,000 par cluster, au détriment de certaines fonctionnalités. Le `ontap-nas-economy` pilote ne prend pas en charge les snapshots granulaires au niveau des volumes Docker ni le clonage.


NOTE: Le `ontap-nas-economy` Le pilote n'est pas pris en charge par Docker Swarm, car Swarm n'effectue pas la création de volumes entre plusieurs nœuds.

Le `ontap-san-economy` pilote crée des volumes Docker en tant que LUN ONTAP au sein d'un pool partagé de volumes FlexVol automatiquement gérés de cette façon. Chaque FlexVol n'est pas limité à une seule LUN et offre une meilleure évolutivité pour les charges de travail SAN. Selon les baies de stockage, ONTAP prend en charge jusqu'à 16384 LUN par cluster. Comme les volumes sont sous-LUN, ce pilote prend en charge les snapshots et le clonage granulaires par volume Docker.

Choisissez le `ontap-nas-flexgroup` pilote pour augmenter le parallélisme vers un volume unique pouvant atteindre plusieurs pétaoctets avec des milliards de fichiers. Les utilisations idéales de FlexGroups sont l'IA, LE ML, le Big Data et l'analytique, les logiciels, le streaming, les référentiels de fichiers, etc. Lors du provisionnement d'un volume FlexGroup, Trident utilise tous les agrégats affectés à un SVM. La prise en charge d'FlexGroup dans Trident comporte également plusieurs considérations :

* Requiert ONTAP version 9.2 ou supérieure
* À ce jour, FlexGroups prend uniquement en charge NFS v3.
* Recommandé pour activer les identifiants NFSv3 64 bits pour la SVM.
* La taille minimale recommandée du membre/volume FlexGroup est de 100 Gio.
* Le clonage n'est pas pris en charge pour les volumes FlexGroup.


Pour plus d'informations sur les FlexGroups et les charges de travail appropriées pour FlexGroups, reportez-vous au https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf["Guide des meilleures pratiques et d'implémentation des volumes NetApp FlexGroup"^] .

Pour bénéficier de fonctionnalités avancées et d'une évolutivité massive dans le même environnement, vous pouvez exécuter plusieurs instances du plug-in de volume Docker, en utilisant une seule instance `ontap-nas` et une autre utilisation `ontap-nas-economy`.



=== Rôle ONTAP personnalisé pour Trident

Vous pouvez créer un rôle de cluster ONTAP avec une Privileges minimale afin de ne pas avoir à utiliser le rôle ONTAP admin pour effectuer des opérations dans Trident. Lorsque vous incluez le nom d'utilisateur dans une configuration Trident backend, Trident utilise le rôle de cluster ONTAP que vous avez créé pour effectuer les opérations.

Pour plus d'informations sur la création de rôles personnalisés Trident, reportez-vous à la sectionlink:https://github.com/NetApp/trident/tree/master/contrib/ontap/trident_role["Générateur de rôle personnalisé Trident"].

[role="tabbed-block"]
====
.Utilisation de l'interface de ligne de commandes ONTAP
--
. Créez un rôle à l'aide de la commande suivante :
+
`security login role create <role_name\> -cmddirname "command" -access all –vserver <svm_name\>`

. Créez un nom d'utilisateur pour l'utilisateur Trident :
+
`security login create -username <user_name\> -application ontapi -authmethod password -role <name_of_role_in_step_1\> –vserver <svm_name\> -comment "user_description"`
`security login create -username <user_name\> -application http -authmethod password -role <name_of_role_in_step_1\> –vserver <svm_name\> -comment "user_description"`

. Mapper le rôle à l'utilisateur :
+
`security login modify username <user_name\> –vserver <svm_name\> -role <role_name\> -application ontapi -application console -authmethod <password\>`



--
.À l'aide de System Manager
--
Dans ONTAP System Manager, effectuez les opérations suivantes :

. *Créer un rôle personnalisé* :
+
.. Pour créer un rôle personnalisé au niveau du cluster, sélectionnez *Cluster > Paramètres*.
+
(Ou) pour créer un rôle personnalisé au niveau du SVM, sélectionner *stockage > Storage VM > >> Paramètres > `required SVM` utilisateurs et rôles*.

.. Sélectionnez l'icône de flèche (*->*) en regard de *utilisateurs et rôles*.
.. Sélectionnez *+Ajouter* sous *rôles*.
.. Définissez les règles du rôle et cliquez sur *Enregistrer*.


. *Mapper le rôle à l'utilisateur Trident*: + effectuez les étapes suivantes sur la page *utilisateurs et rôles* :
+
.. Sélectionnez Ajouter l'icône *+* sous *utilisateurs*.
.. Sélectionnez le nom d'utilisateur requis et sélectionnez un rôle dans le menu déroulant pour *role*.
.. Cliquez sur *Enregistrer*.




--
====
Pour plus d'informations, reportez-vous aux pages suivantes :

* link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/FAQ__Custom_roles_for_administration_of_ONTAP["Rôles personnalisés pour l'administration de ONTAP"^] ou link:https://docs.netapp.com/us-en/ontap/authentication/define-custom-roles-task.html["Définissez des rôles personnalisés"^]
* link:https://docs.netapp.com/us-en/ontap-automation/rest/rbac_roles_users.html#rest-api["Travaillez avec les rôles et les utilisateurs"^]




=== Exemples de fichiers de configuration ONTAP

.Exemple NFS pour le <code>ontap-nas</code> pilote
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "defaults": {
      "size": "10G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
====
.Exemple NFS pour le <code>ontap-nas-flexgroup</code> pilote
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-flexgroup",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "defaults": {
      "size": "100G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
====
.Exemple NFS pour le <code>ontap-nas-economy</code> pilote
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1"
}
----
====
.Exemple iSCSI pour le <code>ontap-san</code> pilote
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "igroupName": "netappdvp"
}
----
====
.Exemple NFS pour le <code>ontap-san-economy</code> pilote
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi_eco",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "igroupName": "netappdvp"
}
----
====
.Exemple NVMe/TCP pour le <code>ontap-san</code> pilote
[%collapsible]
====
[listing]
----
{
  "version": 1,
  "backendName": "NVMeBackend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "svm": "svm_nvme",
  "username":"vsadmin",
  "password":"password",
  "sanType": "nvme",
  "useREST": true
}
----
====
.Exemple SCSI sur FC pour le pilote <code> ONTAP-</code>
[%collapsible]
====
[listing]
----
{
  "version": 1,
  "backendName": "ontap-san-backend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "sanType": "fcp",
  "svm": "trident_svm",
  "username":"vsadmin",
  "password":"password",
  "useREST": true
}
----
====


== Configuration logicielle Element

Outre les valeurs de configuration globale, lorsque le logiciel Element (NetApp HCI/SolidFire) est utilisé, ces options sont disponibles.

[cols="3*"]
|===
| Option | Description | Exemple 


| `Endpoint`  a| 
\https://<login>:<password>@<mvip>/json-rpc/<element-version>
 a| 
\https://admin:admin@192.168.160.3/json-rpc/8.0



| `SVIP`  a| 
Port et adresse IP iSCSI
 a| 
10.0.0.7:3260



| `TenantName`  a| 
Locataire SolidFireF à utiliser (créé s'il n'est pas trouvé)
 a| 
`docker`



| `InitiatorIFace`  a| 
Spécifiez l'interface lors de la restriction du trafic iSCSI à une interface non-par défaut
 a| 
`default`



| `Types`  a| 
Spécifications de QoS
 a| 
Voir l'exemple ci-dessous



| `LegacyNamePrefix`  a| 
Préfixe des installations Trident mises à niveau. Si vous avez utilisé une version de Trident antérieure à la version 1.3.2 et effectué une mise à niveau avec des volumes existants, vous devez définir cette valeur pour accéder aux anciens volumes mappés avec la méthode nom-volume.
 a| 
`netappdvp-`

|===
Le `solidfire-san` Le pilote ne prend pas en charge Docker Swarm.



=== Exemple de fichier de configuration du logiciel Element

[listing]
----
{
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://admin:admin@192.168.160.3/json-rpc/8.0",
    "SVIP": "10.0.0.7:3260",
    "TenantName": "docker",
    "InitiatorIFace": "default",
    "Types": [
        {
            "Type": "Bronze",
            "Qos": {
                "minIOPS": 1000,
                "maxIOPS": 2000,
                "burstIOPS": 4000
            }
        },
        {
            "Type": "Silver",
            "Qos": {
                "minIOPS": 4000,
                "maxIOPS": 6000,
                "burstIOPS": 8000
            }
        },
        {
            "Type": "Gold",
            "Qos": {
                "minIOPS": 6000,
                "maxIOPS": 8000,
                "burstIOPS": 10000
            }
        }
    ]
}
----