---
sidebar: sidebar 
permalink: trident-docker/upgrade-uninstall-docker.html 
keywords: uninstall, Trident, trident for docker, docker, upgrade trident for docker 
summary: 'Vous pouvez mettre à niveau Trident pour Docker en toute sécurité, sans impact sur les volumes utilisés. Au cours du processus de mise à niveau, les `docker volume` commandes dirigées vers le plug-in ne réussiront pas et les applications ne pourront pas monter les volumes tant que le plug-in ne sera pas exécuté à nouveau. Dans la plupart des cas, c"est une question de secondes.' 
---
= Mise à niveau ou désinstallation de Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez mettre à niveau Trident pour Docker en toute sécurité, sans impact sur les volumes utilisés. Au cours du processus de mise à niveau, les `docker volume` commandes dirigées vers le plug-in ne réussiront pas et les applications ne pourront pas monter les volumes tant que le plug-in ne sera pas exécuté à nouveau. Dans la plupart des cas, c'est une question de secondes.



== Mise à niveau

Effectuez les étapes ci-dessous pour mettre à niveau Trident pour Docker.

.Étapes
. Lister les volumes existants :
+
[listing]
----
docker volume ls
DRIVER              VOLUME NAME
netapp:latest       my_volume
----
. Désactivez le plug-in :
+
[listing]
----
docker plugin disable -f netapp:latest
docker plugin ls
ID                  NAME                DESCRIPTION                          ENABLED
7067f39a5df5        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
----
. Mettez à niveau le plug-in :
+
[listing]
----
docker plugin upgrade --skip-remote-check --grant-all-permissions netapp:latest netapp/trident-plugin:21.07
----
+

NOTE: La version 18.01 de Trident remplace nDVP. Vous devez effectuer une mise à niveau directe de l' `netapp/ndvp-plugin`image vers l' `netapp/trident-plugin`image.

. Activer le plug-in :
+
[listing]
----
docker plugin enable netapp:latest
----
. Vérifiez que le plug-in est activé :
+
[listing]
----
docker plugin ls
ID                  NAME                DESCRIPTION                             ENABLED
7067f39a5df5        netapp:latest       Trident - NetApp Docker Volume Plugin   true
----
. Vérifier que les volumes sont visibles :
+
[listing]
----
docker volume ls
DRIVER              VOLUME NAME
netapp:latest       my_volume
----



IMPORTANT: Si vous effectuez une mise à niveau d'une ancienne version de Trident (antérieure à 20.10) vers Trident 20.10 ou une version ultérieure, vous risquez de générer une erreur. Pour plus d'informations, reportez-vous link:known-issues-docker.html["Problèmes connus"^]à . Si vous entrez dans l'erreur, vous devez d'abord désactiver le plug-in, puis supprimer le plug-in, puis installer la version Trident requise en passant un paramètre de configuration supplémentaire : `docker plugin install netapp/trident-plugin:20.10 --alias netapp --grant-all-permissions config=config.json`



== Désinstaller

Procédez comme suit pour désinstaller Trident pour Docker.

.Étapes
. Supprimez tous les volumes créés par le plug-in.
. Désactivez le plug-in :
+
[listing]
----
docker plugin disable netapp:latest
docker plugin ls
ID                  NAME                DESCRIPTION                          ENABLED
7067f39a5df5        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
----
. Retirez le plug-in :
+
[listing]
----
docker plugin rm netapp:latest
----

