---
sidebar: sidebar 
permalink: faq.html 
keywords: faq, frequently asked questions 
summary: 'Trouvez les réponses aux questions fréquemment posées sur l"installation, la configuration, la mise à niveau et le dépannage de Trident.' 
---
= Foire aux questions
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Trouvez les réponses aux questions fréquemment posées sur l'installation, la configuration, la mise à niveau et le dépannage de Trident.



== Questions générales



=== À quelle fréquence le Trident est-il commercialisé ?

Trident est commercialisé tous les quatre mois à partir de la version 24.02 : février, juin et octobre.



=== Trident prend-il en charge toutes les fonctionnalités publiées dans une version spécifique de Kubernetes ?

Trident ne prend généralement pas en charge les fonctionnalités alpha dans Kubernetes. Trident peut prendre en charge les fonctionnalités bêta dans les deux versions de Trident, qui suivent la version bêta de Kubernetes.



=== Le fonctionnement de Trident dépend-il d'autres produits NetApp ?

Trident ne dépend d'aucun autre produit logiciel NetApp et fonctionne comme une application autonome. Toutefois, vous devez disposer d'un système de stockage back-end NetApp.



=== Comment puis-je obtenir des informations complètes sur la configuration de Trident ?

Utilisez `tridentctl get` la commande pour obtenir plus d'informations sur votre configuration Trident.



=== Puis-je obtenir des indicateurs sur le provisionnement du stockage par Trident ?

Oui. Les terminaux Prometheus peuvent être utilisés pour rassembler des informations sur les opérations Trident, telles que le nombre de systèmes back-end gérés, le nombre de volumes provisionnés, d'octets consommés, etc. Vous pouvez également l'utiliser link:https://docs.netapp.com/us-en/cloudinsights/["Cloud Insights"^] pour la surveillance et l'analyse.



=== L'expérience utilisateur change-t-elle lors de l'utilisation de Trident en tant que mécanisme de provisionnement CSI ?

Non. Il n'y a pas de changement en ce qui concerne l'expérience utilisateur et les fonctionnalités. Le nom de provisionneur utilisé est `csi.trident.netapp.io`. Cette méthode d'installation de Trident est recommandée si vous souhaitez utiliser toutes les nouvelles fonctionnalités fournies par les versions actuelles et futures.



== Installez et utilisez Trident sur un cluster Kubernetes



=== Trident prend-il en charge une installation hors ligne à partir d'un registre privé ?

Oui, Trident peut être installé hors ligne. Reportez-vous à la link:../trident-get-started/kubernetes-deploy.html["En savoir plus sur l'installation de Trident"^].



=== Puis-je installer Trident à distance ?

Oui. Trident 18.10 et les versions ultérieures prennent en charge la fonctionnalité d'installation à distance à partir de n'importe quelle machine ayant `kubectl` accès au cluster. Une fois l' `kubectl`accès vérifié (par exemple, lancez une `kubectl get nodes` commande à partir de l'ordinateur distant pour vérifier), suivez les instructions d'installation.



=== Puis-je configurer la haute disponibilité avec Trident ?

Trident est installé en tant que déploiement Kubernetes (ReplicaSet) avec une instance. Sa haute disponibilité est donc intégrée. Vous ne devez pas augmenter le nombre de répliques dans le déploiement. Si le nœud sur lequel Trident est installé est perdu ou si le pod est inaccessible, Kubernetes redéploie automatiquement le pod vers un nœud sain dans le cluster. Trident est un plan de contrôle uniquement. Les pods actuellement montés ne sont donc pas affectés si Trident est redéployé.



=== Trident a-t-il besoin d'accéder à l'espace de noms du système kube ?

Trident lit depuis le serveur d'API Kubernetes pour déterminer quand les applications demandent de nouvelles ESV et doit donc accéder à kube-system.



=== Quels sont les rôles et les Privileges utilisés par Trident ?

Le programme d'installation Trident crée un Kubernetes ClusterRole, qui dispose d'un accès spécifique aux ressources PersistentVolume, PersistentVolumeClaim, StorageClass et Secret du cluster Kubernetes. link:trident-get-started/kubernetes-customize-deploy-tridentctl.html["Personnalisez l'installation tridentctl"^] .



=== Puis-je générer localement les fichiers de manifeste exacts que Trident utilise pour l'installation ?

Vous pouvez, si nécessaire, générer et modifier localement les fichiers de manifeste exacts que Trident utilise pour l'installation. Reportez-vous à la link:trident-get-started/kubernetes-customize-deploy-tridentctl.html["Personnalisez l'installation tridentctl"^].



=== Puis-je partager le même SVM back-end ONTAP pour deux instances Trident distinctes pour deux clusters Kubernetes distincts ?

Bien qu'il ne soit pas conseillé, vous pouvez utiliser la même SVM back-end pour deux instances Trident. Spécifiez un nom de volume unique pour chaque instance lors de l'installation et/ou spécifiez un paramètre unique `StoragePrefix` dans `setup/backend.json` le fichier. Cela permet de s'assurer que le même FlexVol volume n'est pas utilisé pour les deux instances.



=== Est-il possible d'installer Trident sous ContainerLinux (anciennement CoreOS) ?

Trident est un pod Kubernetes qui peut être installé quel que soit l'emplacement d'exécution de Kubernetes.



=== Puis-je utiliser Trident avec NetApp Cloud Volumes ONTAP ?

Oui, Trident est pris en charge sur AWS, Google Cloud et Azure.



=== Trident est-il compatible avec Cloud Volumes Services ?

Oui, Trident prend en charge le service Azure NetApp Files dans Azure ainsi que le Cloud Volumes Service dans GCP.



== Dépannage et support



=== NetApp prend-il en charge Trident ?

Bien que Trident soit open source et gratuit, NetApp le prend entièrement en charge, à condition que votre back-end NetApp soit pris en charge.



=== Comment puis-je soulever un dossier de demande de support ?

Pour soulever un dossier de support, effectuez l'une des opérations suivantes :

. Contactez votre support Account Manager pour obtenir de l'aide pour créer un dossier.
. Pour ouvrir un dossier de demande de support, contactez https://www.netapp.com/company/contact-us/support/["Support NetApp"^].




=== Comment générer un bundle de journaux de support ?

Vous pouvez créer un bundle de support en exécutant `tridentctl logs -a`. Outre les journaux capturés dans le pack, capture le journal kubelet pour diagnostiquer les problèmes de montage côté Kubernetes. Les instructions d'obtention du journal kubelet varient en fonction de l'installation de Kubernetes.



=== Que faire si j'ai besoin de demander une nouvelle fonctionnalité ?

Créez un problème https://github.com/NetApp/trident["Trident Github"^] et mentionnez *RFE* dans l'objet et la description du problème.



=== Où puis-je soulever un défaut ?

Créez un problème sur https://github.com/NetApp/trident["Trident Github"^]. Veillez à inclure toutes les informations et tous les journaux nécessaires concernant le problème.



=== Que se passe-t-il si j'ai une brève question sur Trident et que j'ai besoin d'éclaircissements ? Y a-t-il une communauté ou un forum?

Pour toute question, problème ou demande, contactez-nous par le biais de notre Trident link:https://discord.gg/NetApp["Déroulez le canal"^]ou GitHub.



=== Le mot de passe de mon système de stockage a changé et Trident ne fonctionne plus. Comment puis-je le récupérer ?

Mettez à jour le mot de passe du back-end avec `tridentctl update backend myBackend -f </path/to_new_backend.json> -n trident`. Remplacement `myBackend` dans l'exemple avec votre nom de back-end, et ``/path/to_new_backend.json` avec le chemin d'accès correct `backend.json` fichier.



=== Trident ne trouve pas mon nœud Kubernetes. Comment résoudre ce problème ?

Trident ne trouve pas de nœud Kubernetes dans deux scénarios possibles. Elle peut être due à un problème de mise en réseau dans Kubernetes ou DNS. Le demonset de nœuds Trident qui s'exécute sur chaque nœud Kubernetes doit pouvoir communiquer avec le contrôleur Trident pour enregistrer le nœud avec Trident. Si des modifications de mise en réseau se sont produites après l'installation de Trident, ce problème survient uniquement avec les nouveaux nœuds Kubernetes ajoutés au cluster.



=== Si le pod Trident est détruit, ces données seront-elles perdues ?

Les données ne seront pas perdues si le pod Trident est détruit. Les métadonnées Trident sont stockées dans des objets CRD. Tous les volumes persistants provisionnés par Trident fonctionneront normalement.



== Mettez à niveau Trident



=== Est-il possible de mettre à niveau une version plus ancienne directement vers une version plus récente (sans passer par quelques versions) ?

NetApp prend en charge la mise à niveau de Trident d'une version majeure vers la prochaine version majeure immédiate. Vous pouvez effectuer la mise à niveau de la version 18.xx vers la version 19.xx, 19.xx vers la version 20.xx, etc. Il est conseillé de tester la mise à niveau dans un laboratoire avant le déploiement en production.



=== Est-il possible de revenir à une version antérieure de Trident ?

Si vous avez besoin d'un correctif pour les bogues observés après une mise à niveau, des problèmes de dépendance ou une mise à niveau non réussie ou incomplète, vous devez link:trident-managing-k8s/uninstall-trident.html["Désinstallez Trident"]réinstaller la version précédente en suivant les instructions spécifiques à cette version. Il s'agit de la seule méthode recommandée pour revenir à une version antérieure.



== Gestion des systèmes back-end et des volumes



=== Dois-je définir à la fois la gestion et les DataLIF dans un fichier de définition ONTAP backend ?

Le LIF de gestion est obligatoire. DataLIF varie :

* San ONTAP : ne spécifiez pas pour iSCSI. Trident utilise link:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["Mappage de LUN sélectif ONTAP"^] pour découvrir les LIF iSCI nécessaires à l'établissement d'une session à chemins multiples. Un avertissement est généré si `dataLIF` est explicitement défini. Voir link:trident-use/ontap-san-examples.html["Options et exemples de configuration des SAN ONTAP"] pour plus de détails.
* NAS ONTAP : NetApp recommande de spécifier `dataLIF`. Si non fourni, Trident récupère les LIFs de données du SVM. Vous pouvez spécifier un nom de domaine complet (FQDN) à utiliser pour les opérations de montage NFS, ce qui vous permet de créer un DNS circulaire pour équilibrer la charge sur plusieurs dataLIFs. Voir link:trident-use/ontap-nas-examples.html["Options et exemples de configuration du NAS ONTAP"]pour plus de détails




=== Trident peut-il configurer CHAP pour les systèmes back-end ONTAP ?

Oui. Trident prend en charge le protocole CHAP bidirectionnel pour les systèmes back-end ONTAP. Ceci nécessite la `useCHAP=true` configuration de votre back-end.



=== Comment gérer les règles d'exportation avec Trident ?

Trident peut créer et gérer de manière dynamique des règles d'exportation à partir de la version 20.04. Cela permet à l'administrateur de stockage de fournir un ou plusieurs blocs CIDR dans leur configuration backend et de laisser Trident ajouter des adresses IP de nœud comprise dans ces plages à une export policy créée. De cette manière, Trident gère automatiquement l'ajout et la suppression de règles pour les nœuds avec des adresses IP dans les délais de modification donnés.



=== Les adresses IPv6 peuvent-elles être utilisées pour les LIF de gestion et de données ?

Trident prend en charge la définition des adresses IPv6 pour :

* `managementLIF` et `dataLIF` Pour les systèmes NAS ONTAP.
* `managementLIF` Pour les systèmes back-end ONTAP SAN. Vous ne pouvez pas spécifier `dataLIF` Sur un SAN backend ONTAP.


Trident doit être installé à l'aide de l'indicateur `--use-ipv6` (pour l' `tridentctl`installation), `IPv6` (pour l'opérateur Trident) ou `tridentTPv6` (pour l'installation Helm) pour qu'il fonctionne sur IPv6.



=== Est-il possible de mettre à jour la LIF de gestion en back-end ?

Oui, il est possible de mettre à jour la LIF de management back-end à l'aide de `tridentctl update backend` commande.



=== Est-il possible de mettre à jour le DataLIF sur le back-end ?

Vous pouvez mettre à jour DataLIF sur `ontap-nas` et `ontap-nas-economy` uniquement.



=== Est-il possible de créer plusieurs systèmes back-end dans Trident pour Kubernetes ?

Trident peut prendre en charge plusieurs systèmes back-end simultanément, avec le même pilote ou des pilotes différents.



=== Comment Trident stocke-t-il les informations d'identification back-end ?

Trident stocke les informations d'identification du back-end en tant que secrets Kubernetes.



=== Comment Trident sélectionne-t-il un back-end spécifique ?

Si les attributs back-end ne peuvent pas être utilisés pour sélectionner automatiquement les pools appropriés pour une classe, l' `storagePools` et `additionalStoragePools` les paramètres sont utilisés pour sélectionner un ensemble spécifique de pools.



=== Comment s'assurer que Trident ne se provisionne pas à partir d'un back-end spécifique ?

Le `excludeStoragePools` paramètre est utilisé pour filtrer l'ensemble de pools que Trident utilise pour le provisionnement et supprime tous les pools correspondant.



=== En cas de systèmes back-end multiples du même type, comment Trident sélectionne-t-il le système back-end à utiliser ?

S'il existe plusieurs systèmes back-end configurés du même type, Trident sélectionne le back-end approprié en fonction des paramètres présents dans `StorageClass` et `PersistentVolumeClaim`. Par exemple, s'il existe plusieurs systèmes back-end de pilotes ONTAP-nas, Trident tente de faire correspondre les paramètres dans le `StorageClass` et le combiné et `PersistentVolumeClaim` un back-end qui peut répondre aux exigences répertoriées dans `StorageClass` le et `PersistentVolumeClaim`le . Si plusieurs systèmes back-end correspondent à la demande, Trident les sélectionne de manière aléatoire.



=== Trident prend-il en charge le protocole CHAP bidirectionnel avec Element/SolidFire ?

Oui.



=== Comment Trident déploie-t-il les qtrees sur un volume ONTAP ? Combien de qtrees peuvent-ils être déployés sur un seul volume ?

Le `ontap-nas-economy` pilote crée jusqu'à 200 qtrees dans le même FlexVol volume (configurable entre 50 et 300), 100,000 qtrees par nœud de cluster et 2,4 millions par cluster. Lorsque vous entrez un nouveau `PersistentVolumeClaim` qui est entretenu par le conducteur économique, le conducteur recherche s'il existe déjà un FlexVol volume qui peut réparer le nouveau qtree. Si le FlexVol volume n'existe pas et peut servir le Qtree, un nouveau FlexVol volume est créé.



=== Comment définir des autorisations Unix pour les volumes provisionnés sur ONTAP NAS ?

Vous pouvez définir des autorisations Unix sur le volume provisionné par Trident en définissant un paramètre dans le fichier de définition back-end.



=== Comment configurer un ensemble explicite d'options de montage NFS ONTAP lors du provisionnement d'un volume ?

Par défaut, Trident ne définit aucune valeur des options de montage sur Kubernetes. Pour spécifier les options de montage dans la classe de stockage Kubernetes, suivez l'exemple donné link:https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-samples/storage-class-ontapnas-k8s1.8-mountoptions.yaml["ici"^].



=== Comment définir les volumes provisionnés sur une export policy spécifique ?

Pour permettre aux hôtes appropriés d'accéder à un volume, utilisez le `exportPolicy` paramètre configuré dans le fichier de définition backend.



=== Comment définir le chiffrement des volumes via Trident avec ONTAP ?

Vous pouvez définir le chiffrement sur le volume provisionné par Trident à l'aide du paramètre de chiffrement dans le fichier de définition back-end. Pour plus d'informations, reportez-vous à : link:trident-reco/security-reco.html#use-trident-with-nve-and-nae["Fonctionnement de Trident avec NVE et NAE"]



=== Quel est le meilleur moyen d'implémenter la QoS pour ONTAP via Trident ?

Utiliser `StorageClasses` Afin d'implémenter la QoS pour ONTAP.



=== Comment spécifier le provisionnement fin ou non fin via Trident ?

Les pilotes ONTAP prennent en charge le provisionnement fin ou non fin. Le provisionnement fin est par défaut pour les pilotes ONTAP. Si un provisionnement lourd est souhaité, vous devez configurer le fichier de définition backend ou le `StorageClass`. Si les deux sont configurés, `StorageClass` a priorité. Configurez les éléments suivants pour ONTAP :

. Marche `StorageClass`, réglez le `provisioningType` attribuer comme épaisseur.
. Dans le fichier de définition back-end, activez les volumes épais par définition `backend spaceReserve parameter` comme volume.




=== Comment puis-je m'assurer que les volumes utilisés ne sont pas supprimés même si je supprime accidentellement le volume de volume persistant ?

La protection contre la demande de volume persistant est automatiquement activée sur Kubernetes à partir de la version 1.10.



=== Puis-je augmenter les ESV NFS créées par Trident ?

Oui. Vous pouvez développer une demande de volume persistant créée par Trident. Notez que la croissance automatique de volume est une fonctionnalité ONTAP qui n'est pas applicable à Trident.



=== Puis-je importer un volume en mode SnapMirror Data protection (DP) ou hors ligne ?

L'importation du volume échoue si le volume externe est en mode DP ou est hors ligne. Vous recevez le message d'erreur suivant :

[listing]
----
Error: could not import volume: volume import failed to get size of volume: volume <name> was not found (400 Bad Request) command terminated with exit code 1.
Make sure to remove the DP mode or put the volume online before importing the volume.
----


=== Comment un quota de ressources est-il traduit-il vers un cluster NetApp ?

Le quota de ressources de stockage Kubernetes doit fonctionner tant que le stockage NetApp possède de la capacité. Lorsque le stockage NetApp ne peut pas respecter les paramètres des quotas Kubernetes en raison d'un manque de capacité, Trident tente de se provisionner, mais des erreurs se produisent.



=== Puis-je créer des copies Snapshot de volume à l'aide de Trident ?

Oui. La création de snapshots de volumes à la demande et de volumes persistants à partir de snapshots sont prises en charge par Trident. Pour créer des volumes persistants à partir de snapshots, assurez-vous que la `VolumeSnapshotDataSource` porte de fonctionnalité a été activée.



=== Quels sont les pilotes qui prennent en charge les copies Snapshot de volume Trident ?

À compter d'aujourd'hui, la prise en charge des instantanés à la demande est disponible pour notre `ontap-nas` , `ontap-nas-flexgroup` , `ontap-san` , `ontap-san-economy` , `solidfire-san` , `gcp-cvs` , et `azure-netapp-files` Pilotes backend.



=== Comment effectuer une sauvegarde Snapshot d'un volume provisionné par Trident avec ONTAP ?

Cette option est disponible sur `ontap-nas`, `ontap-san`, et `ontap-nas-flexgroup` pilotes. Vous pouvez également spécifier un `snapshotPolicy` pour le `ontap-san-economy` Pilote au niveau FlexVol.

Cela est également disponible sur les `ontap-nas-economy` pilotes, mais au niveau de la granularité FlexVol volume, et non au niveau qtree. Pour activer la fonction de snapshot des volumes provisionnés par Trident, définissez l'option du paramètre back-end `snapshotPolicy` sur la règle de snapshot souhaitée, comme défini sur le back-end ONTAP. Les snapshots pris par le contrôleur de stockage ne sont pas connus par Trident.



=== Puis-je définir un pourcentage de réserve Snapshot pour un volume provisionné via Trident ?

Oui, vous pouvez réserver un pourcentage spécifique d'espace disque pour stocker les copies Snapshot via Trident en définissant l' `snapshotReserve`attribut dans le fichier de définition back-end. Si vous avez configuré `snapshotPolicy` et `snapshotReserve` dans le fichier de définition back-end, le pourcentage de réserve de snapshots est défini en fonction du `snapshotReserve` pourcentage mentionné dans le fichier back-end. Si le `snapshotReserve` pourcentage n'est pas mentionné, ONTAP utilise par défaut le pourcentage de réserve d'instantanés à 5. Si l' `snapshotPolicy`option est définie sur aucun, le pourcentage de réserve d'instantanés est défini sur 0.



=== Puis-je accéder directement au répertoire de snapshot de volume et copier les fichiers ?

Oui, vous pouvez accéder au répertoire de snapshots sur le volume provisionné par Trident en paramétrant le `snapshotDir` paramètre dans le fichier de définition backend.



=== Puis-je configurer SnapMirror pour les volumes via Trident ?

Actuellement, SnapMirror doit être défini en externe via l'interface de ligne de commande ONTAP ou OnCommand System Manager.



=== Comment restaurer des volumes persistants à un snapshot ONTAP spécifique ?

Pour restaurer un volume sur un snapshot ONTAP, effectuez les opérations suivantes :

. Arrêter le pod d'application qui utilise le volume persistant.
. Restaurez les données vers le snapshot requis via l'interface de ligne de commande de ONTAP ou OnCommand System Manager.
. Redémarrez le pod d'application.




=== Trident peut-il provisionner des volumes sur des SVM dont un miroir de partage de charge est configuré ?

Des miroirs de partage de charge peuvent être créés pour les volumes root des SVM qui fournissent des données sur NFS. ONTAP met automatiquement à jour les miroirs de partage de charge pour les volumes qui ont été créés par Trident. Cela peut entraîner des retards dans le montage des volumes. Lorsque plusieurs volumes sont créés via Trident, le provisionnement d'un volume dépend de la mise à jour par ONTAP du miroir de partage de charge.



=== Comment puis-je séparer l'utilisation de la classe de stockage pour chaque client/locataire ?

Kubernetes n'autorise pas les classes de stockage dans les espaces de noms. Toutefois, vous pouvez utiliser Kubernetes pour limiter l'utilisation d'une classe de stockage spécifique par espace de noms à l'aide de quotas de ressources de stockage, qui sont par espace de noms. Pour refuser un accès d'espace de noms spécifique à un stockage spécifique, définissez le quota de ressources sur 0 pour cette classe de stockage.
