---
sidebar: sidebar 
permalink: trident-rn.html 
keywords: 'what"s new, new features, enhancements, known issues, resolved issues, troubleshooting' 
summary: NetApp améliore et améliore continuellement ses produits et services. Voici quelques-unes des dernières fonctionnalités, améliorations et correctifs de la dernière version de Trident. 
---
= Quoi de neuf
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Les notes de publication fournissent des informations sur les nouvelles fonctionnalités, les améliorations et les correctifs de bogues de la dernière version de NetApp Trident.


WARNING: Le `tridentctl` Binaire pour Linux fourni dans le fichier zip du programme d'installation est la version testée et prise en charge. Sachez que le `macos` binaire fourni dans le `/extras` une partie du fichier zip n'est pas testée ou prise en charge.



== Quoi de neuf dans la version 25.10 ?

Découvrez les nouveautés de Trident et Trident Protect, notamment les améliorations, les correctifs et les fonctionnalités obsolètes.



=== Trident



==== Améliorations

* *Kubernetes* :
+
** Ajout de la prise en charge des instantanés de groupes de volumes CSI avec les API Kubernetes d'instantanés de groupes de volumes v1beta1 pour les pilotes ONTAP-NAS NFS et ONTAP-SAN-Economy, en plus de ONTAP-SAN (iSCSI et FC). Voirlink:https://docs.netapp.com/us-en/trident/trident-use/vol-group-snapshots.html["Travailler avec des instantanés de groupes de volumes"^] .
** Ajout de la prise en charge du basculement automatique de la charge de travail avec détachement forcé du volume pour les pilotes ONTAP-NAS et ONTAP-NAS-Economy (à l'exclusion de SMB dans les deux pilotes NAS), ainsi que pour les pilotes ONTAP-SAN et ONTAP-SAN-Economy. Voirlink:https://docs.netapp.com/us-en/trident/trident-reco/force-detach.html["Automatisation du basculement des applications avec état grâce à Trident"^] .
** Amélioration de la concurrence des nœuds Trident pour une meilleure évolutivité des opérations sur les nœuds pour les volumes FCP.
** Ajout de la prise en charge ONTAP AFX pour le pilote ONTAP NAS. Voirlink:https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html["Options et exemples de configuration du NAS ONTAP"^] .
** Ajout de la prise en charge de la configuration des demandes et des limites de ressources CPU et mémoire pour les conteneurs Trident via les valeurs CR et Helm du graphique TridentOrchestrator. (link:https://github.com/NetApp/trident/issues/1000["Numéro 1000"] ,link:https://github.com/NetApp/trident/issues/927["Numéro 927"] ,link:https://github.com/NetApp/trident/issues/853["Numéro 853"] ,link:https://github.com/NetApp/trident/issues/592["Numéro 592"] ,link:https://github.com/NetApp/trident/issues/110["Numéro 110"] ).
** Ajout de la prise en charge FC pour la personnalité ASAr2. Voirlink:https://docs.netapp.com/us-en/trident/trident-use/ontap-san-examples.html["Options et exemples de configuration des SAN ONTAP"^] .
** Ajout d'une option permettant de diffuser les métriques Prometheus via HTTPS au lieu de HTTP. Voirlink:https://docs.netapp.com/us-en/trident/trident-use/monitor-trident.html["Surveillez Trident"^] .
** Ajout d'une option `--no-rename` lors de l'importation d'un volume pour conserver le nom d'origine mais laisser Trident gérer le cycle de vie du volume. Voirlink:https://docs.netapp.com/us-en/trident/trident-use/vol-import.html["Importer des volumes"^] .
** Le déploiement de Trident s'exécute désormais au niveau de priorité « system-cluster-critical ».


* Ajout d'une option permettant au contrôleur Trident d'utiliser le réseau hôte via Helm, l'opérateur et Tridentctl (link:https://github.com/NetApp/trident/issues/858["Numéro 858"] ).
* Ajout d'une prise en charge manuelle de la QoS au pilote ANF, le rendant prêt pour la production dans Trident 25.10 ; cette amélioration expérimentale a été introduite dans Trident 25.06.




==== Améliorations expérimentales


NOTE: Ne pas utiliser dans des environnements de production.

* *[Aperçu technique]* : Ajout de la prise en charge de la concurrence pour ONTAP-NAS (NFS uniquement) et ONTAP-SAN (NVMe pour ONTAP 9 unifié), en plus de l'aperçu technique existant pour le pilote ONTAP-SAN (protocoles iSCSI et FCP dans ONTAP 9 unifié).




==== Correctifs

* **Kubernetes** :
+
** Correction de l'incohérence du nom du conteneur CSI node-driver-registrar en normalisant Linux DaemonSet en node-driver-registrar pour correspondre à la dénomination des images de conteneurs et de DaemonSet Windows.
** Correction d'un problème où les politiques d'exportation pour les qtrees hérités n'étaient pas correctement mises à jour.


* *Openshift* :
+
** Correction d'un problème de démarrage du pod de nœud Trident sur les nœuds Windows dans Openshift dû au fait que SCC avait allowHostDirVolumePlugin défini sur false (link:https://github.com/NetApp/trident/issues/950["Numéro 950"] ).


* Correction du problème de configuration du QPS de l'API Kubernetes via Helm (link:https://github.com/NetApp/trident/issues/975["Numéro 975"] ).
* Correction d'un problème d'impossibilité de monter une revendication de volume persistant (PVC) basée sur un instantané d'un système de fichiers XFS basé sur NVMe PVC sur le même nœud Kubernetes.
* Correction d'un problème de changement d'UUID après le redémarrage de l'hôte/Docker en mode NDVP en ajoutant des noms de sous-système uniques/partagés par backend (par exemple, netappdvp_subsystem).
* Correction des erreurs de montage pour les volumes iSCSI lors de la mise à niveau de Trident des versions antérieures à 23.10 vers la version 24.10 et supérieures, résolution du problème « SANType invalide ».
* Correction d'un problème où l'état du backend Trident ne passait pas à l'état en ligne/hors ligne sans redémarrage du contrôleur Trident .
* Correction d'un problème de concurrence intermittent provoquant un redimensionnement lent des PVC.
* Correction d'un problème où les instantanés n'étaient pas supprimés en cas d'échec de clonage de volume.
* Correction d'un problème empêchant la désactivation du volume lorsque son chemin d'accès au périphérique était modifié par le noyau.
* Correction d'un problème de désinstallation du volume dû à un périphérique LUKS déjà fermé.
* Correction d'un problème où des opérations de stockage lentes entraînaient des erreurs ContextDeadline.
* L'opérateur Trident attendra un délai d'expiration k8s configurable pour vérifier la version de Trident .




=== Protéger Trident

NetApp Trident Protect propose des fonctionnalités avancées de gestion des données applicatives qui améliorent la fonctionnalité et la disponibilité des applications Kubernetes avec état reposant sur les systèmes de stockage NetApp ONTAP et le mécanisme de provisionnement du stockage NetApp Trident CSI.



==== Améliorations

* Ajout d'annotations pour contrôler les délais d'expiration des CR d'instantané pour les CR planifiées et de sauvegarde :
+
** `protect.trident.netapp.io/snapshot-completion-timeout`
** `protect.trident.netapp.io/volume-snapshots-ready-to-use-timeout`
** `protect.trident.netapp.io/volume-snapshots-created-timeout`
+
Voirlink:https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-protect-apps.html["Prise en charge des annotations de sauvegarde et de planification"^] .



* Ajout d'une annotation à la CR planifiée pour configurer le délai d'expiration de la liaison PVC, qui sera utilisé par la CR de sauvegarde : `protect.trident.netapp.io/pvc-bind-timeout-sec` . Voirlink:https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-protect-apps.html["Prise en charge des annotations de sauvegarde et de planification"^] .
* Amélioré `tridentctl-protect` Listes de sauvegardes et d'instantanés avec un nouveau champ pour indiquer les échecs des hooks d'exécution.




== Modifications apportées le 25/06/2020



=== Trident



==== Correctifs

* *Kubernetes* : problème critique résolu où des périphériques iSCSI incorrects étaient découverts lors du détachement de volumes des nœuds Kubernetes.




== Modifications dans la version 25.06.1



=== Trident


IMPORTANT: Pour les clients utilisant SolidFire, veuillez ne pas effectuer la mise à niveau vers la version 25.06.1 en raison d'un problème connu lors de la dépublication des volumes.  La version 25.06.2 sera bientôt publiée pour résoudre ce problème.



==== Correctifs

* *Kubernetes* :
+
** Correction d'un problème où les NQN n'étaient pas vérifiés avant d'être démappés des sous-systèmes.
** Correction d'un problème où plusieurs tentatives de fermeture d'un périphérique LUKS entraînaient des échecs lors du détachement des volumes.
** Correction du volume iSCSI non mis en scène lorsque le chemin du périphérique a changé depuis sa création.
** Clonage de blocs de volumes sur plusieurs classes de stockage.


* *OpenShift* : un problème a été résolu où la préparation du nœud iSCSI échouait avec OCP 4.19.
* Augmentation du délai d'expiration lors du clonage d'un volume à l'aide des backends SolidFire (link:https://github.com/NetApp/trident/issues/1008["Question no 1008"] ).




== Modifications dans la version 25.06



=== Trident



==== Améliorations

* *Kubernetes* :
+
** Ajout de la prise en charge des instantanés de groupe de volumes CSI avec  `v1beta1` API Kubernetes d'instantané de groupe de volumes pour le pilote iSCSI ONTAP-SAN. Voir link:https://docs.netapp.com/us-en/trident/trident-use/vol-group-snapshots.html["Travailler avec des instantanés de groupes de volumes"^].
+

NOTE: VolumeGroupSnapshot est une fonctionnalité bêta de Kubernetes avec des API bêta. Kubernetes 1.32 est la version minimale requise pour VolumeGroupSnapshot.

** Ajout de la prise en charge d' ONTAP ASA r2 pour NVMe/TCP en plus d'iSCSI. Voirlink:https://docs.netapp.com/us-en/trident/trident-use/ontap-san-examples.html["Options et exemples de configuration des SAN ONTAP"^] .
** Prise en charge SMB sécurisée ajoutée pour les volumes ONTAP-NAS et ONTAP-NAS-Economy. Les utilisateurs et groupes Active Directory peuvent désormais être utilisés avec les volumes SMB pour une sécurité renforcée. Voir link:https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-prep.html#enable-secure-smb["Activer le SMB sécurisé"^].
** Concurrence de nœud Trident améliorée pour une plus grande évolutivité des opérations de nœud pour les volumes iSCSI.
** Ajouté  `--allow-discards` lors de l'ouverture des volumes LUKS pour autoriser les commandes discard/TRIM pour la récupération d'espace.
** Performances améliorées lors du formatage des volumes chiffrés LUKS.
** Nettoyage LUKS amélioré pour les périphériques LUKS défaillants mais partiellement formatés.
** Idempotence de nœud Trident améliorée pour la connexion et le détachement de volumes NVMe.
** Ajouté  `internalID` champ à la configuration du volume Trident pour le pilote ONTAP-SAN-Economy.
** Ajout de la prise en charge de la réplication de volume avec SnapMirror pour les backends NVMe. Voir link:https://docs.netapp.com/us-en/trident/trident-use/vol-volume-replicate.html["Réplication de volumes à l'aide de SnapMirror"^].






==== Améliorations expérimentales


NOTE: Ne pas utiliser dans des environnements de production.

* [Aperçu technique] Opérations simultanées du contrôleur Trident activées via le  `--enable-concurrency` Indicateur de fonctionnalité. Cela permet aux opérations du contrôleur de s'exécuter en parallèle, améliorant ainsi les performances dans les environnements très fréquentés ou de grande taille.
+

NOTE: Cette fonctionnalité est expérimentale et prend actuellement en charge des flux de travail parallèles limités avec le pilote ONTAP-SAN (protocoles iSCSI et FCP).

* [Aperçu technique] Ajout de la prise en charge manuelle du QOS avec le pilote ANF.




==== Correctifs

* *Kubernetes* :
+
** Correction d'un problème avec CSI NodeExpandVolume où les périphériques multi-chemins pouvaient être laissés avec des tailles incongrues lorsque les disques SCSI sous-jacents n'étaient pas disponibles.
** Correction de l'échec de nettoyage des politiques d'exportation en double pour les pilotes ONTAP-NAS et ONTAP-NAS-Economy.
** Volumes GCNV fixes par défaut sur NFSv3 lorsque  `nfsMountOptions` n'est pas défini ; les protocoles NFSv3 et NFSv4 sont désormais pris en charge. Si  `nfsMountOptions` n'est pas fourni, la version NFS par défaut de l'hôte (NFSv3 ou NFSv4) sera utilisée.
** Problème de déploiement résolu lors de l'installation de Trident à l'aide de Kustomize ( link:https://github.com/NetApp/trident/issues/831["Question no 831"] ).
** Correction des politiques d'exportation manquantes pour les PVC créés à partir d'instantanés ( link:https://github.com/NetApp/trident/issues/1016["Question no 1016"] ).
** Problème résolu où les tailles de volume ANF ne sont pas automatiquement alignées sur des incréments de 1 Gio.
** Problème résolu lors de l'utilisation de NFSv3 avec Bottlerocket.


* Problème résolu avec les volumes ONTAP-NAS-Economy s'étendant jusqu'à 300 To malgré les échecs de redimensionnement.
* Problème résolu où les opérations de division de clone étaient effectuées de manière synchrone lors de l'utilisation de l'API REST ONTAP.




==== Obsolescences :

* *Kubernetes* : mise à jour de la version minimale prise en charge de Kubernetes vers la version 1.27.




=== Protéger Trident

NetApp Trident Protect propose des fonctionnalités avancées de gestion des données applicatives qui améliorent la fonctionnalité et la disponibilité des applications Kubernetes avec état reposant sur les systèmes de stockage NetApp ONTAP et le mécanisme de provisionnement du stockage NetApp Trident CSI.



==== Améliorations

* Temps de restauration améliorés, offrant la possibilité d'effectuer des sauvegardes complètes plus fréquentes.
* Granularité améliorée de la définition de l'application et restauration sélective avec filtrage Groupe-Version-Type (GVK).
* Resynchronisation et réplication inverse efficaces lors de l'utilisation d'AppMirrorRelationship (AMR) avec NetApp SnapMirror, pour éviter la réplication PVC complète.
* Ajout de la possibilité d'utiliser l'identité du pod EKS pour créer des compartiments AppVault, supprimant ainsi la nécessité de spécifier un secret avec les informations d'identification du compartiment pour les clusters EKS.
* Ajout de la possibilité d'ignorer la restauration des étiquettes et des annotations dans l'espace de noms de restauration, si nécessaire.
* AppMirrorRelationship (AMR) vérifiera désormais l'extension du PVC source et effectuera l'extension appropriée sur le PVC de destination si nécessaire.




==== Correctifs

* Correction d'un bug où les valeurs d'annotation des instantanés précédents étaient appliquées aux instantanés plus récents. Toutes les annotations d'instantanés sont désormais correctement appliquées.
* Un secret a été défini pour le chiffrement du Data Mover (Kopia / Restic) par défaut, s'il n'est pas défini.
* Ajout de messages de validation et d'erreur améliorés pour la création d'appvault S3.
* AppMirrorRelationship (AMR) réplique désormais uniquement les PV dans l'état lié, pour éviter les tentatives infructueuses.
* Problème résolu où des erreurs s'affichaient lors de l'obtention d'AppVaultContent sur un AppVault avec un grand nombre de sauvegardes.
* Les instantanés VMSnapshots KubeVirt sont exclus des opérations de restauration et de basculement pour éviter les échecs.
* Problème résolu avec Kopia où les instantanés étaient supprimés prématurément en raison du calendrier de conservation par défaut de Kopia remplaçant ce qui avait été défini par l'utilisateur dans le calendrier.




== Changements en 25.02.1



=== Trident



==== Correctifs

* *Kubernetes* :
+
** Correction d'un problème dans l'opérateur Trident où les noms et les versions des images sidecar étaient mal renseignés lors de l'utilisation d'un registre d'images non par défaut (link:https://github.com/NetApp/trident/issues/983["Question no 983"]).
** Résolution du problème d'échec de restauration des sessions multivoies lors d'un retour de basculement ONTAP (link:https://github.com/NetApp/trident/issues/961["Question no 961"]).






== Changements en 25.02

Depuis Trident 25.02, le récapitulatif des nouveautés fournit des informations détaillées sur les améliorations, les correctifs et les descriptions des versions Trident et Trident Protect.



=== Trident



==== Améliorations

* *Kubernetes* :
+
** Prise en charge de ONTAP ASA r2 pour iSCSI ajoutée.
** Ajout de la prise en charge du détachement forcé pour les volumes ONTAP-NAS pendant les scénarios d'arrêt de nœud non normal. Les nouveaux volumes ONTAP-NAS utiliseront désormais des règles d'exportation par volume gérées par Trident. Chemin de mise à niveau fourni pour les volumes existants afin qu'ils puissent passer au nouveau modèle de règle d'export lors de l'annulation de la publication sans affecter les workloads actifs.
** Ajout d'une annotation cloneFromSnapshot.
** Prise en charge supplémentaire du clonage de volumes inter-espaces de noms.
** L'analyse d'auto-rétablissement iSCSI améliorée corrige les problèmes pour lancer des renumérisations par hôte, canal, cible et ID de LUN exacts.
** Prise en charge de Kubernetes 1.32.


* *OpenShift* :
+
** Ajout de la prise en charge de la préparation automatique des nœuds iSCSI pour RHCOS sur les clusters ROSA.
** Ajout de la prise en charge de la virtualisation OpenShift pour les pilotes ONTAP.


* Ajout de la prise en charge Fibre Channel sur le pilote ONTAP-SAN.
* Ajout de la prise en charge de NVMe LUKS.
* Passe à l'image de travail pour toutes les images de base.
* Ajout de la détection et de la journalisation de l'état de la connexion iSCSI lorsque les sessions iSCSI doivent être connectées mais ne sont pas (link:https://github.com/NetApp/trident/issues/961["Question no 961"]).
* Ajout de la prise en charge des volumes SMB avec le pilote google-cloud-NetApp-volumes
* Prise en charge supplémentaire permettant aux volumes ONTAP d'ignorer la file d'attente de restauration lors de la suppression.
* Ajout d'une prise en charge pour remplacer les images par défaut à l'aide de Shas au lieu de balises.
* Ajout de l'indicateur image-pull-secrets au programme d'installation de tridentctl.




==== Correctifs

* *Kubernetes* :
+
** Correction des adresses IP de nœud manquantes des règles d'exportation automatique (link:https://github.com/NetApp/trident/issues/965["Question no 965"]).
** Correction des règles d'exportation automatique pour passer prématurément à une règle de volume pour ONTAP-NAS-Economy.
** Les informations d'identification de configuration du back-end ont été corrigées pour prendre en charge toutes les partitions ARN AWS disponibles (link:https://github.com/NetApp/trident/issues/913["Question no 913"]).
** Ajout d'une option pour désactiver la réconciliation automatique du configurateur dans l'opérateur Trident (link:https://github.com/NetApp/trident/issues/924["Question no 924"]).
** Ajout de securityContext pour conteneur csi-resizer (link:https://github.com/NetApp/trident/issues/976["Question no 976"]).






=== Protéger Trident

NetApp Trident Protect propose des fonctionnalités avancées de gestion des données applicatives qui améliorent la fonctionnalité et la disponibilité des applications Kubernetes avec état reposant sur les systèmes de stockage NetApp ONTAP et le mécanisme de provisionnement du stockage NetApp Trident CSI.



==== Améliorations

* Ajout de la prise en charge des sauvegardes et des restaurations pour les machines virtuelles de virtualisation KubeVirt/OpenShift pour le stockage volumeMode : fichier et volumeMode : bloc (périphérique brut). Cette prise en charge est compatible avec tous les pilotes Trident et améliore les fonctionnalités de protection existantes lors de la réplication du stockage à l'aide de NetApp SnapMirror avec Trident Protect.
* Ajout de la fonctionnalité de contrôle du comportement de gel au niveau des applications pour les environnements Kubevirt.
* Ajout de la prise en charge de la configuration des connexions proxy AutoSupport.
* Ajout de la capacité à définir un secret pour le cryptage des Data Movers (Kopia/Restic).
* Ajout de la possibilité d'exécuter manuellement un crochet d'exécution.
* Ajout de la possibilité de configurer des contraintes de contexte de sécurité (CSC) lors de l'installation de Trident Protect.
* Ajout de la prise en charge de la configuration de NodeSelector lors de l'installation de Trident Protect.
* Ajout de la prise en charge du proxy de sortie HTTP/HTTPS pour les objets AppVault.
* Filtre de ressources étendu pour permettre l'exclusion des ressources du cluster-scoped.
* Ajout de la prise en charge du jeton de session AWS dans les informations d'identification d'AppVault S3.
* Ajout de la prise en charge de la collecte de ressources après les crochets d'exécution pré-snapshot.




==== Correctifs

* Amélioration de la gestion des volumes temporaires pour ignorer la file d'attente de restauration du volume ONTAP.
* Les annotations SCC sont désormais restaurées aux valeurs d'origine.
* Amélioration de l'efficacité des restaurations grâce à la prise en charge des opérations parallèles.
* Prise en charge améliorée des délais d'expiration du crochet d'exécution pour les applications de plus grande taille.




== Changements en 24.10.1



=== Améliorations

* *Kubernetes* : prise en charge supplémentaire de Kubernetes 1.32.
* Ajout de la détection et de la journalisation de l'état de la connexion iSCSI lorsque les sessions iSCSI doivent être connectées mais ne sont pas (link:https://github.com/NetApp/trident/issues/961["Question no 961"]).




=== Correctifs

* Correction des adresses IP de nœud manquantes des règles d'exportation automatique (link:https://github.com/NetApp/trident/issues/965["Question no 965"]).
* Correction des règles d'exportation automatique pour passer prématurément à une règle de volume pour ONTAP-NAS-Economy.
* Mise à jour des dépendances Trident et Trident-ASUP pour corriger CVE-2024-45337 et CVE-2024-45310.
* Déconnexion supprimée des portails non CHAP défectueux par intermittence pendant l'auto-rétablissement iSCSI (link:https://github.com/NetApp/trident/issues/961["Question no 961"]).




== Changements en 24.10



=== Améliorations

* Le pilote Google Cloud NetApp volumes est désormais disponible pour les volumes NFS et prend en charge le provisionnement avec détection de zone.
* L'identité de workload GCP sera utilisée comme identité cloud pour les volumes NetApp de Google Cloud avec GKE.
* Ajout d'un `formatOptions` paramètre de configuration aux pilotes ONTAP-SAN et ONTAP-SAN-Economy pour permettre aux utilisateurs de spécifier les options de format de LUN.
* Taille minimale du volume Azure NetApp Files réduite à 50 Gio. La nouvelle taille minimale d'Azure devrait être globalement disponible en novembre.
* Ajout d'un `denyNewVolumePools` paramètre de configuration pour limiter les pilotes ONTAP-NAS-Economy et ONTAP-SAN-Economy aux pools FlexVol préexistants.
* Détection supplémentaire pour l'ajout, la suppression ou le renommage d'agrégats du SVM sur tous les pilotes ONTAP
* Ajout de 18 Mio de surcharge aux LUN LUKS pour garantir que la taille du PVC signalée est utilisable.
* Amélioration de la gestion des étapes et des déconnexions des nœuds ONTAP-SAN et ONTAP-SAN-Economy pour permettre le retrait des périphériques après une phase d'échec.
* Ajout d'un générateur de rôles personnalisé permettant aux clients de créer un rôle minimaliste pour Trident dans ONTAP.
* Ajout d'une journalisation supplémentaire pour le dépannage `lsscsi` (link:https://github.com/NetApp/trident/issues/792["Question no 792"]).




==== Kubernetes

* Ajout de nouvelles fonctionnalités Trident pour les workflows natifs Kubernetes :
+
** Protection des données
** Migration des données
** Reprise après incident
** Mobilité des applications
+
link:./trident-protect/learn-about-trident-protect.html["En savoir plus sur Trident Protect"].



* Ajout d'un nouveau drapeau `--k8s-api-qps` aux installateurs de définir la valeur QPS utilisée par Trident pour communiquer avec le serveur API Kubernetes.
* Indicateur ajouté `--node-prep` aux programmes d'installation pour la gestion automatique des dépendances des protocoles de stockage sur les nœuds de cluster Kubernetes. Compatibilité testée et vérifiée avec le protocole de stockage iSCSI Amazon Linux 2023
* Ajout de la prise en charge du détachement forcé pour les volumes ONTAP-NAS-Economy dans les scénarios d'arrêt de nœud non normal.
* Les nouveaux volumes NFS ONTAP-NAS-Economy utiliseront des règles d'export par qtree lors de l'utilisation de `autoExportPolicy` l'option backend. Les qtrees ne sont mappés sur des règles d'exportation restrictives du nœud qu'au moment de la publication, afin d'améliorer le contrôle d'accès et la sécurité. Lorsque Trident supprime le volume de tous les nœuds, les qtrees existants sont basculés vers le nouveau modèle de règles d'export pour le faire, sans impact sur les workloads actifs.
* Prise en charge de Kubernetes 1.31.




==== Améliorations expérimentales

* Ajout d'un aperçu technique de la prise en charge de Fibre Channel sur le pilote ONTAP-SAN.




=== Correctifs

* *Kubernetes* :
+
** Crochet d'admission fixe de Rancher empêchant les installations de Trident Helm (link:https://github.com/NetApp/trident/issues/839["Question no 839"]).
** Clé d'affinité fixe dans les valeurs du graphique Helm (link:https://github.com/NetApp/trident/issues/898["Question no 898"]).
** Fixed tridentControllerPluginNodeSelector/tridentNodePluginNodeSelector ne fonctionnera pas avec la valeur "true" (link:https://github.com/NetApp/trident/issues/899["Question no 899"]).
** Les snapshots éphémères créés lors du clonage () ont été suppriméslink:https://github.com/NetApp/trident/issues/901["Question no 901"].


* Ajout de la prise en charge de Windows Server 2019.
* Fixe `Go mod Tidy` dans Trident repo (link:https://github.com/NetApp/trident/issues/767["Question no 767"]).




=== Dérations

* *Kubernetes:*
+
** Mise à jour de la version 1.25 de Kubernetes minimale prise en charge.
** Suppression de la prise en charge de la stratégie de sécurité POD.






=== Changement de marque du produit

À partir de la version 24.10, Astra Trident a été renommée Trident (NetApp Trident). Ce changement de marque n'affecte en rien les fonctionnalités, les plateformes prises en charge ou l'interopérabilité pour Trident.



== Changements en 24.06



=== Améliorations

* **IMPORTANT** : le `limitVolumeSize` paramètre limite désormais la taille qtree/LUN dans les pilotes économiques ONTAP. Utilisez le nouveau  `limitVolumePoolSize` paramètre pour contrôler les tailles de FlexVol dans ces pilotes. (link:https://github.com/NetApp/trident/issues/341["Question no 341"]).
* Ajout de la fonctionnalité d'auto-rétablissement iSCSI pour lancer des analyses SCSI par ID de LUN exact si des igroups obsolètes sont en cours d'utilisation (link:https://github.com/NetApp/trident/issues/883["Question no 883"]).
* Prise en charge supplémentaire des opérations de clonage de volume et de redimensionnement même lorsque le back-end est en mode suspendu.
* Ajout de la possibilité de propager les paramètres de journal configurés par l'utilisateur pour le contrôleur Trident aux pods de nœud Trident.
* Ajout de la prise en charge dans Trident pour utiliser REST par défaut au lieu de ONTAPI (ZAPI) pour ONTAP versions 9.15.1 et ultérieures.
* Prise en charge des noms de volumes et des métadonnées personnalisés sur les systèmes back-end de stockage ONTAP pour les nouveaux volumes persistants.
* Amélioration du `azure-netapp-files` pilote (ANF) pour activer automatiquement le répertoire de snapshots par défaut lorsque les options de montage NFS sont définies pour utiliser la version 4.x.
* Ajout de la prise en charge de BottlerRocket pour les volumes NFS.
* Ajout de la prise en charge des aperçus techniques de Google Cloud NetApp volumes.




==== Kubernetes

* Prise en charge de Kubernetes 1.30.
* Ajout de la capacité de Trident DemonSet à nettoyer les montages zombies et les fichiers de suivi résiduels au démarrage (link:https://github.com/NetApp/trident/issues/883["Question no 883"]).
* Ajout d'une annotation PVC `trident.netapp.io/luksEncryption` pour l'importation dynamique de volumes LUKS (link:https://github.com/NetApp/trident/issues/849["Question no 849"]).
* Prise en compte de la topologie du pilote ANF.
* Ajout de la prise en charge des nœuds Windows Server 2022.




=== Correctifs

* Correction des défaillances d'installation de Trident suite à des transactions obsolètes.
* Correction de tridentctl pour ignorer les messages d'avertissement de Kubernetes (link:https://github.com/NetApp/trident/issues/892["Question no 892"]).
* La priorité du contrôleur Trident a été modifiée `SecurityContextConstraint` en `0` (link:https://github.com/NetApp/trident/issues/887["Question no 887"]).
* Les pilotes ONTAP acceptent désormais les tailles de volume inférieures à 20 Mio ( link:https://github.com/NetApp/trident/issues/885["Problème[#885"] ).
* Correction de la Trident pour empêcher la réduction des volumes FlexVol pendant le redimensionnement du pilote ONTAP-SAN.
* Correction de la défaillance d'importation du volume ANF avec NFS v4.1.




== Changements en 24.02



=== Améliorations

* Prise en charge supplémentaire de Cloud Identity.
+
** AKS avec ANF : Azure Workload Identity sera utilisé comme identité cloud.
** EKS avec FSxN : le rôle IAM AWS sera utilisé comme identité cloud.


* Ajout de la prise en charge de l'installation de Trident en tant que module complémentaire sur le cluster EKS à partir de la console EKS.
* Ajout de la possibilité de configurer et de désactiver l'auto-rétablissement iSCSI (link:https://github.com/NetApp/trident/issues/864["Question no 864"]).
* Ajout de la personnalité d'Amazon FSX aux pilotes ONTAP pour permettre l'intégration avec AWS IAM et SecretsManager, et pour permettre à Trident de supprimer des volumes FSX avec des sauvegardes (link:https://github.com/NetApp/trident/issues/453["Question no 453"]).




==== Kubernetes

* Prise en charge de Kubernetes 1.29.




=== Correctifs

* Correction des messages d'avertissement ACP lorsque ACP n'est pas activé (link:https://github.com/NetApp/trident/issues/866["Question no 866"]).
* Ajout d'un délai de 10 secondes avant d'effectuer une répartition des clones lors de la suppression d'un snapshot pour les pilotes ONTAP, lorsqu'un clone est associé au snapshot.




=== Dérations

* Suppression de l'infrastructure d'attepostes in-to des manifestes d'images multi-plates-formes.




== Changements en 23.10



=== Correctifs

* Extension de volume fixe si la nouvelle taille demandée est inférieure à la taille totale des volumes pour les pilotes de stockage ontap-nas et ontap-nas-flexgroup (link:https://github.com/NetApp/trident/issues/834["Question no 834"^]).
* Taille de volume fixe pour afficher uniquement la taille utilisable du volume lors de l'importation pour les pilotes de stockage ontap-nas et ontap-nas-flexgroup (link:https://github.com/NetApp/trident/issues/722["Question no 722"^]).
* Conversion de noms FlexVol fixes pour ONTAP-NAS-Economy.
* Correction du problème d'initialisation Trident sur un nœud Windows lors du redémarrage du nœud.




=== Améliorations



==== Kubernetes

Prise en charge de Kubernetes 1.28.



==== Trident

* Ajout de la prise en charge de l'utilisation d'ami (Azure Managed identités) avec le pilote de stockage Azure-netapp-Files.
* Ajout de la prise en charge de NVMe over TCP pour le pilote ONTAP-SAN
* Ajout de la possibilité de suspendre le provisionnement d'un volume lorsque le back-end est défini sur suspendu par l'utilisateur (link:https://github.com/NetApp/trident/issues/558["Question no 558"^]).




== Changements en 23.07.1

*Kubernetes:* Suppression fixe du démonset pour prendre en charge les mises à niveau sans temps d'arrêt (link:https://github.com/NetApp/trident/issues/740["Question no 740"^]).



== Changements en 23.07



=== Correctifs



==== Kubernetes

* Correction de la mise à niveau de Trident pour ignorer les anciens pods bloqués en état de terminaison (link:https://github.com/NetApp/trident/issues/740["Question no 740"^]).
* Ajout d'une tolérance à la définition de « passagent-trident-version-pod » (link:https://github.com/NetApp/trident/issues/795["Question no 795"^]).




==== Trident

* Correction des demandes ONTAPI (ZAPI) pour s'assurer que les numéros de série des LUN sont interrogés lors de l'obtention des attributs de LUN pour identifier et corriger les périphériques iSCSI fantômes lors des opérations de transfert des nœuds.
* Correction de la gestion des erreurs dans le code du pilote de stockage (link:https://github.com/NetApp/trident/issues/816["Question no 816"^]).
* Redimensionnement des quotas fixes lors de l'utilisation de pilotes ONTAP avec use-REST=true.
* Création de clones LUN fixes dans ontap-san-Economy.
* Annuler la publication du champ d'informations de `rawDevicePath` à `devicePath`; logique ajoutée pour remplir et récupérer (dans certains cas) `devicePath` légale.




=== Améliorations



==== Kubernetes

* Prise en charge supplémentaire de l'importation de snapshots préprovisionnés.
* Déploiement réduit et autorisations linux diaboconfigurées (link:https://github.com/NetApp/trident/issues/817["Question no 817"^]).




==== Trident

* Ne rapporte plus le champ d'état pour les volumes et les snapshots « en ligne ».
* Met à jour l'état du back-end si le back-end ONTAP est hors ligne (link:https://github.com/NetApp/trident/issues/801["Questions #801"^], link:https://github.com/NetApp/trident/issues/543["#543"^]).
* Le numéro de série de la LUN est toujours récupéré et publié au cours du workflow ControllerVolumePublish.
* Ajout d'une logique supplémentaire pour vérifier le numéro de série et la taille du périphérique iSCSI à chemins d'accès multiples.
* Vérification supplémentaire des volumes iSCSI pour s'assurer que le périphérique multiacheminement correct n'est pas mis en place.




==== Amélioration expérimentale

Ajout de la prise en charge de la présentation technique de NVMe over TCP pour le pilote ONTAP-SAN.



==== Documentation

De nombreuses améliorations de l'organisation et du formatage ont été apportées.



=== Dérations



==== Kubernetes

* Suppression de la prise en charge des snapshots v1beta1.
* Suppression de la prise en charge des volumes et des classes de stockage pré-CSI.
* Mise à jour de la version 1.22 de Kubernetes minimale prise en charge.




== Changements en 23.04


IMPORTANT: Forcer le détachement de volume pour les volumes ONTAP-SAN-* est uniquement pris en charge avec les versions Kubernetes avec le volet fonctionnalité de fermeture de nœud non gracieuse activé. Le détachement forcé doit être activé au moment de l'installation à l'aide du `--enable-force-detach` Indicateur du programme d'installation Trident.



=== Correctifs

* Correction de l'opérateur Trident pour utiliser IPv6 localhost pour l'installation lorsqu'il est spécifié dans spec.
* Correction des autorisations de rôle de cluster de l'opérateur Trident pour qu'elles soient synchronisées avec les autorisations du bundle (link:https://github.com/NetApp/trident/issues/799["Question no 799"^]).
* Résolution du problème de connexion d'un volume de bloc brut sur plusieurs nœuds en mode RWX.
* Prise en charge du clonage FlexGroup fixe et importation de volumes pour les volumes SMB.
* Résolution du problème où le contrôleur Trident n'a pas pu s'arrêter immédiatement (link:https://github.com/NetApp/trident/issues/811["Question no 811"]).
* Correctif ajouté pour afficher la liste de tous les noms de groupes initiateur associés à une LUN spécifiée provisionnée avec des pilotes ontap-san-*.
* Ajout d'un correctif pour permettre l'exécution des processus externes.
* Erreur de compilation corrigée pour l'architecture s390 (link:https://github.com/NetApp/trident/issues/537["Question no 537"]).
* Correction d'un niveau de journalisation incorrect lors des opérations de montage de volume (link:https://github.com/NetApp/trident/issues/781["Question no 781"]).
* Correction de l'erreur d'assertion de type de potentiel (link:https://github.com/NetApp/trident/issues/802["Question no 802"]).




=== Améliorations

* Kubernetes :
+
** Prise en charge de Kubernetes 1.27.
** Ajout de la prise en charge de l'importation de volumes LUKS.
** Ajout de la prise en charge du mode d'accès PVC ReadWriteOncePod.
** Ajout de la prise en charge du détachement forcé pour les volumes ONTAP-SAN-* lors des scénarios d'arrêt de nœud non gracieuse.
** Tous les volumes ONTAP-SAN-* utiliseront désormais les groupes initiateurs par nœud. Les LUN ne seront mappées qu'aux igroups dont la publication est active sur ces nœuds afin d'améliorer notre niveau de sécurité. Les volumes existants seront basculés de manière opportuniste vers le nouveau schéma d'igroup lorsque Trident détermine qu'il est possible de le faire sans incidence sur les workloads actifs (link:https://github.com/NetApp/trident/issues/758["Question no 758"]).
** Amélioration de la sécurité de Trident en nettoyant les groupes initiateurs gérés par Trident non utilisés à partir de systèmes back-end ONTAP-SAN-*.


* Ajout de la prise en charge des volumes SMB avec Amazon FSX aux pilotes de stockage ontap-nas-Economy et ontap-nas-flexgroup.
* Ajout de la prise en charge des partages SMB avec les pilotes de stockage ontap-nas, ontap-nas-Economy et ontap-nas-flexgroup.
* Ajout de la prise en charge des nœuds arm64 (link:https://github.com/NetApp/trident/issues/732["Question no 732"]).
* La procédure d'arrêt de Trident a été améliorée en désactivant d'abord les serveurs d'API (link:https://github.com/NetApp/trident/issues/811["Question no 811"]).
* Ajout de la prise en charge de la construction multi plate-forme pour les hôtes Windows et arm64 à Makefile ; voir BUILD.md.




=== Dérations

**Kubernetes:** les igroups Backend-scoped ne seront plus créés lors de la configuration de pilotes ontap-san et ontap-san-Economy (link:https://github.com/NetApp/trident/issues/758["Question no 758"]).



== Changements en 23.01.1



=== Correctifs

* Correction de l'opérateur Trident pour utiliser IPv6 localhost pour l'installation lorsqu'il est spécifié dans spec.
* Correction des autorisations de rôle de cluster opérateur Trident synchronisées avec les autorisations de bundle link:https://github.com/NetApp/trident/issues/799["Question no 799"^].
* Ajout d'un correctif pour permettre l'exécution des processus externes.
* Résolution du problème de connexion d'un volume de bloc brut sur plusieurs nœuds en mode RWX.
* Prise en charge du clonage FlexGroup fixe et importation de volumes pour les volumes SMB.




== Changements en 23.01


IMPORTANT: Kubernetes 1.27 est désormais pris en charge dans Trident. Veuillez mettre à niveau Trident avant de mettre à niveau Kubernetes.



=== Correctifs

* Kubernetes : ajout d'options pour exclure la création de règles de sécurité du Pod pour réparer les installations Trident via Helm (link:https://github.com/NetApp/trident/issues/794["Questions #783, #794"^]).




=== Améliorations

.Kubernetes
* Prise en charge ajoutée de Kubernetes 1.26.
* Amélioration de l'utilisation globale des ressources RBAC Trident (link:https://github.com/NetApp/trident/issues/757["Numéro 757"^]).
* Automatisation ajoutée pour détecter et corriger les sessions iSCSI interrompues ou obsolètes sur les nœuds hôtes.
* Ajout de la prise en charge de l'extension des volumes chiffrés LUKS.
* Kubernetes : ajout de la prise en charge de la rotation des identifiants pour les volumes chiffrés LUKS.


.Trident
* Ajout de la prise en charge des volumes SMB avec Amazon FSX for NetApp ONTAP au pilote de stockage ONTAP-nas.
* Ajout de la prise en charge des autorisations NTFS lors de l'utilisation de volumes SMB.
* Ajout de la prise en charge des pools de stockage pour les volumes GCP avec le niveau de service CVS.
* Ajout de la prise en charge de l'utilisation facultative de flexgroupAgrégateList lors de la création de FlexGroups avec le pilote de stockage ontap-nas-flexgroup.
* Meilleures performances du pilote de stockage économique ONTAP-nas lors de la gestion de plusieurs volumes FlexVol
* Mises à jour des donnéesLIF activées pour tous les pilotes de stockage NAS de ONTAP.
* Mise à jour de la convention de nommage Trident Deployment and DemonSet afin de refléter le système d'exploitation du nœud hôte.




=== Dérations

* Kubernetes : mise à jour de Kubernetes minimale prise en charge vers la version 1.21.
* Les DataLIFs ne doivent plus être spécifiées lors de la configuration des `ontap-san` pilotes ou `ontap-san-economy`.




== Changements en 22.10

*Vous devez lire les informations critiques suivantes avant de passer à Trident 22.10.*

[WARNING]
.<strong> informations sur Trident 22,10 </strong>
====
* Kubernetes 1.25 est désormais pris en charge par Trident. Vous devez effectuer une mise à niveau de Trident vers la version 22.10 avant de passer à Kubernetes 1.25.
* Trident applique désormais strictement l'utilisation de la configuration de chemins d'accès multiples dans les environnements SAN, avec une valeur recommandée de `find_multipaths: no` dans le fichier multipath.conf.
+
Utilisation d'une configuration sans chemins d'accès multiples ou de l'utilisation de `find_multipaths: yes` ou `find_multipaths: smart` la valeur du fichier multipath.conf entraînera des échecs de montage. Trident a recommandé l'utilisation de `find_multipaths: no` depuis la version 21.07.



====


=== Correctifs

* Problème spécifique au système ONTAP back-end créé à l'aide de `credentials` le champ ne s'est pas connecté pendant la mise à niveau 22.07.0 (link:https://github.com/NetApp/trident/issues/759["Numéro 759"^]).
* **Docker:** correction d'un problème entraînant l'échec du démarrage du plug-in de volume Docker dans certains environnements (link:https://github.com/NetApp/trident/issues/548["Numéro 548"^] et link:https://github.com/NetApp/trident/issues/760["Numéro 760"^]).
* Correction du problème SLM spécifique aux systèmes back-end SAN ONTAP pour garantir que seul un sous-ensemble de LIFs de données appartenant aux nœuds de reporting est publié.
* Problème de performances résolu lors de la connexion d'un volume à des analyses inutiles des LUN iSCSI.
* Suppression des tentatives granulaires dans le flux de travail Trident iSCSI pour échouer rapidement et réduire les intervalles de tentatives externes.
* Résolution du problème lorsqu'une erreur a été renvoyée lors du vidage d'un périphérique iSCSI lorsque le périphérique multivoie correspondant a déjà été rincé.




=== Améliorations

* Kubernetes :
+
** Prise en charge ajoutée de Kubernetes 1.25. Vous devez effectuer une mise à niveau de Trident vers la version 22.10 avant de passer à Kubernetes 1.25.
** Ajout d'un ServiceAccount, ClusterRole et ClusterRoleBinding distincts pour Trident Deployment et DemonSet afin de permettre des améliorations futures des autorisations.
** Prise en charge ajoutée de link:https://docs.netapp.com/us-en/trident/trident-use/volume-share.html["partage de volume entre espaces de noms"].


* Tout Trident `ontap-*` Les pilotes de stockage fonctionnent désormais avec l'API REST de ONTAP.
* Ajout d'un nouvel opérateur yaml (`bundle_post_1_25.yaml`) sans a. `PodSecurityPolicy` Pour la prise en charge de Kubernetes 1.25.
* Ajouté link:https://docs.netapp.com/us-en/trident/trident-reco/security-luks.html["Prise en charge des volumes LUKS-chiffrés"] pour `ontap-san` et `ontap-san-economy` lecteurs de stockage
* Ajout de la prise en charge des nœuds Windows Server 2019.
* Ajouté link:https://docs.netapp.com/us-en/trident/trident-use/anf.html["Prise en charge des volumes SMB sur les nœuds Windows"] grâce au `azure-netapp-files` pilote de stockage
* La détection automatique du basculement MetroCluster pour les pilotes ONTAP est désormais disponible dans l'ensemble.




=== Dérations

* **Kubernetes:** mise à jour du nombre minimum de Kubernetes pris en charge vers 1.20.
* Suppression du pilote ADS (Data Store).
* Retrait du support pour `yes` et `smart` options pour `find_multipaths` Lors de la configuration des chemins d'accès multiples du nœud de travail pour iSCSI.




== Changements en 22.07



=== Correctifs

**Kubernetes**

* Problème résolu pour gérer les valeurs booléennes et nombres pour le sélecteur de nœud lors de la configuration de Trident avec Helm ou l'opérateur Trident. (link:https://github.com/NetApp/trident/issues/700["Problème GitHub n° 700"^])
* Résolution du problème lors de la gestion des erreurs provenant d'un chemin non CHAP, de sorte que kubelet réessaie en cas d'échec. link:https://github.com/NetApp/trident/issues/736["Problème GitHub n° 736"^])




=== Améliorations

* Passer de k8s.gcr.io au registre.k8s.io comme registre par défaut pour les images CSI
* Les volumes ONTAP-SAN utiliseront désormais des igroups par nœud et ne mapperont les LUN aux groupes initiateurs, tout en les ayant été publiés activement à ces nœuds pour améliorer notre sécurité. Lorsque Trident détermine que les volumes existants sont sécurisés, sans affecter les workloads actifs, les volumes existants seront transférés de manière opportuniste vers le nouveau modèle d'groupe initiateur.
* Inclus un quota de Resourcequota avec les installations Trident pour s'assurer que Trident DemonSet est planifié lorsque la consommation PriorityClass est limitée par défaut.
* Ajout de la prise en charge des fonctions réseau au pilote Azure NetApp Files. (link:https://github.com/NetApp/trident/issues/717["Problème GitHub n° 717"^])
* Ajout de la détection automatique du basculement MetroCluster dans l'aperçu technique aux pilotes ONTAP. (link:https://github.com/NetApp/trident/issues/228["Problème GitHub n° 228"^])




=== Dérations

* **Kubernetes:** mise à jour du nombre minimum de Kubernetes pris en charge vers 1.19.
* La configuration backend n'autorise plus plusieurs types d'authentification dans la configuration unique.




=== Suppressions

* Le pilote CVS AWS (obsolète depuis 22.04) a été supprimé.
* Kubernetes
+
** Suppression des capacités SYS_ADMIN inutiles des modules de nœud.
** Réduit la préparation des nœuds afin de simplifier les informations sur l'hôte et la détection des services actifs pour obtenir la confirmation de la disponibilité des services NFS/iSCSI sur les nœuds workers.






=== Documentation

Une nouvelle link:https://docs.netapp.com/us-en/trident/trident-reference/pod-security.html["Normes de sécurité du pod"]section (PSS) détaillant les autorisations activées par Trident lors de l'installation a été ajoutée.



== Changements en 22.04

NetApp améliore et améliore continuellement ses produits et services. Voici quelques-unes des dernières fonctionnalités de Trident. Pour les versions précédentes, reportez-vous à https://docs.netapp.com/us-en/trident/earlier-versions.html["Versions antérieures de la documentation"].


IMPORTANT: Si vous effectuez une mise à niveau à partir d'une version précédente de Trident et que vous utilisez Azure NetApp Files, le ``location`` le paramètre config est désormais un champ singleton obligatoire.



=== Correctifs

* Amélioration de l'analyse des noms d'initiateurs iSCSI. (link:https://github.com/NetApp/trident/issues/681["Problème GitHub n° 681"^])
* Problème résolu lorsque les paramètres de classe de stockage CSI n'étaient pas autorisés. (link:https://github.com/NetApp/trident/issues/598["Problème GitHub n° 598"^])
* Déclaration de clé en double fixe dans Trident CRD. (link:https://github.com/NetApp/trident/issues/671["Problème GitHub n° 671"^])
* Correction des journaux CSI instantanés erronés. (link:https://github.com/NetApp/trident/issues/629["Problème GitHub n° 629"^]))
* Résolution du problème lié à l'annulation de la publication des volumes sur les nœuds supprimés. (link:https://github.com/NetApp/trident/issues/691["Problème GitHub n° 691"^])
* Ajout de la gestion des incohérences du système de fichiers sur les périphériques en bloc. (link:https://github.com/NetApp/trident/issues/656["Problème GitHub n° 656"^])
* Problème résolu extraction automatique des images lors de la configuration du `imageRegistry` indicateur pendant l'installation. (link:https://github.com/NetApp/trident/issues/715["Problème GitHub n° 715"^])
* Résolution du problème d'échec du clonage d'un volume avec plusieurs règles d'exportation par le pilote Azure NetApp Files.




=== Améliorations

* Les connexions entrantes aux terminaux sécurisés de Trident requièrent désormais un minimum de TLS 1.3. (link:https://github.com/NetApp/trident/issues/698["Problème GitHub n° 698"^])
* Trident ajoute désormais des en-têtes HSTS aux réponses à partir de ses terminaux sécurisés.
* Trident tente désormais d'activer automatiquement la fonctionnalité d'autorisations unix Azure NetApp Files.
* *Kubernetes*: Trident demonset s'exécute maintenant dans la classe de priorité critique du nœud système. (link:https://github.com/NetApp/trident/issues/694["Problème GitHub n° 694"^])




=== Suppressions

Le pilote E-Series (désactivé depuis 20.07) a été supprimé.



== Changements en 22.01.1



=== Correctifs

* Résolution du problème lié à l'annulation de la publication des volumes sur les nœuds supprimés. (link:https://github.com/NetApp/trident/issues/691["Problème GitHub n° 691"])
* Panique fixe lors de l'accès aux champs nuls pour l'espace global dans les réponses de l'API ONTAP.




== Changements en 22.01.0



=== Correctifs

* *Kubernetes:* augmentez le temps de rétentative de rétro-enregistrement des nœuds pour les grands clusters.
* Problème résolu dans lequel le pilote Azure-netapp-Files pourrait être confondu avec plusieurs ressources avec le même nom.
* Les DataLIFs IPv6 SAN ONTAP fonctionnent désormais si elles sont spécifiées avec des crochets.
* Problème résolu lors de la tentative d'importation d'un volume déjà importé renvoie EOF laissant le PVC à l'état en attente. (link:https://github.com/NetApp/trident/issues/489["Problème GitHub n° 489"])
* Problème résolu lorsque le ralentissement des performances Trident ralentit lors de la création de plus de 32 snapshots sur un volume SolidFire.
* SHA-1 remplacé par SHA-256 lors de la création du certificat SSL.
* Correction du pilote Azure NetApp Files pour permettre la duplication des noms de ressources et limiter les opérations à un seul emplacement.
* Correction du pilote Azure NetApp Files pour permettre la duplication des noms de ressources et limiter les opérations à un seul emplacement.




=== Améliorations

* Améliorations de Kubernetes :
+
** Prise en charge ajoutée de Kubernetes 1.23.
** Ajoutez des options de planification pour les pods Trident lorsqu'ils sont installés via l'opérateur Trident ou Helm. (link:https://github.com/NetApp/trident/issues/651["Problème GitHub n° 651"^])


* Autorisation des volumes inter-régions dans le pilote GCP (link:https://github.com/NetApp/trident/issues/633["Problème GitHub n° 633"^])
* Ajout de la prise en charge de l'option 'unixPermissionss' aux volumes Azure NetApp Files. (link:https://github.com/NetApp/trident/issues/666["Problème GitHub n° 666"^])




=== Dérations

L'interface REST de Trident peut écouter et servir uniquement aux adresses 127.0.0.1 ou [::1]



== Changements en 21.10.1


WARNING: La version v21.10.0 présente un problème qui peut placer le contrôleur Trident dans un état CrashLoopBackOff lorsqu'un nœud est supprimé, puis réintégré au cluster Kubernetes. Ce problème a été résolu dans la version 1.210.1 (édition GitHub 669).



=== Correctifs

* Condition de race potentielle fixe lors de l'importation d'un volume sur un back-end Cloud CVS GCP, entraînant l'échec de l'importation.
* Résolution d'un problème de mise en service du contrôleur Trident dans un état CashLoopBackOff lorsqu'un nœud est retiré, puis réintégré au cluster Kubernetes (problème GitHub 669).
* Problème résolu : les SVM n'ont plus été découverts si aucun nom de SVM n'a été spécifié (problème GitHub 612).




== Changements en 21.10.0



=== Correctifs

* Problème résolu : les clones de volumes XFS n'ont pas pu être montés sur le même nœud que le volume source (problème GitHub 514).
* Résolution du problème dans lequel Trident a consigné une erreur fatale à l'arrêt (problème GitHub 597).
* Correctifs liés à Kubernetes :
+
** Renvoyer l'espace utilisé d'un volume comme taille de restauration minimale lors de la création de snapshots avec `ontap-nas` et `ontap-nas-flexgroup` Pilotes (problème GitHub 645).
** Résolution du problème où `Failed to expand filesystem` Une erreur a été consignée après le redimensionnement du volume (problème GitHub 560).
** Résolution du problème de blocage d'un module `Terminating` État (problème GitHub 572).
** A résolu le cas où un `ontap-san-economy` FlexVol peut contenir des LUN de snapshot (GitHub : édition 533).
** Résolution du problème d'installation YAML personnalisé avec une image différente (problème GitHub 613).
** Calcul de la taille de snapshot fixe (problème GitHub 611).
** Résolution du problème lié à l'identification par tous les programmes d'installation de Trident de type Kubernetes standard en tant qu'OpenShift (problème GitHub 639).
** A corrigé l'opérateur Trident pour arrêter la réconciliation si le serveur d'API Kubernetes est inaccessible (problème GitHub 599).






=== Améliorations

* Prise en charge ajoutée de `unixPermissions` Option pour les volumes de performance GCP-CVS.
* Ajout de la prise en charge des volumes CVS optimisés pour l'évolutivité dans GCP dans la plage de 600 Gio à 1 Tio.
* Améliorations liées à Kubernetes :
+
** Prise en charge ajoutée de Kubernetes 1.22.
** Compatibilité de l'opérateur Trident et du tableau Helm avec Kubernetes 1.22 (problème GitHub 628).
** Ajout d'une image opérateur à `tridentctl` Commande images (problème GitHub 570).






=== Améliorations expérimentales

* Ajout de la prise en charge de la réplication de volume dans `ontap-san` conducteur.
* Ajout de la prise en charge de REST * TECH Preview* pour `ontap-nas-flexgroup`, `ontap-san`, et `ontap-nas-economy` pilotes.




== Problèmes connus

Les problèmes connus identifient les problèmes susceptibles de vous empêcher d'utiliser le produit avec succès.

* Lors de la mise à niveau d'un cluster Kubernetes de la version 1.24 vers la version 1.25 ou ultérieure sur lequel Trident est installé, vous devez mettre à jour values.yaml pour définir `excludePodSecurityPolicy` sur `true` ou ajouter la `--set excludePodSecurityPolicy=true` `helm upgrade` commande avant de pouvoir mettre à niveau le cluster.
* Trident applique maintenant un espace vide `fsType` (`fsType=""`) pour les volumes qui n'ont pas `fsType` spécifié dans leur classe de stockage. Avec Kubernetes 1.17 ou version ultérieure, Trident prend en charge la fourniture d'un espace vide `fsType` pour les volumes NFS. Pour les volumes iSCSI, vous devez définir le `fsType` sur votre classe de stockage lors de l'application d'un à l'aide d'un `fsGroup` contexte de sécurité.
* Lors de l'utilisation d'un système back-end sur plusieurs instances Trident, chaque fichier de configuration back-end doit avoir `storagePrefix` une valeur différente pour les systèmes ONTAP back-end ou être utilisé différemment `TenantName` pour les systèmes SolidFire back-end. Trident ne peut pas détecter les volumes créés par d'autres instances de Trident. La tentative de création d'un volume existant sur un système ONTAP ou SolidFire back-end réussit, car Trident considère la création de volume comme une opération puissante. Si `storagePrefix` ou `TenantName` ne diffèrent pas, il peut y avoir des collisions de nom pour les volumes créés sur le même backend.
* Lorsque vous installez Trident (à l'aide de `tridentctl` ou de l'opérateur Trident) et que vous utilisez `tridentctl` pour gérer Trident, vous devez vous assurer que la `KUBECONFIG` variable d'environnement est définie. Ceci est nécessaire pour indiquer le cluster Kubernetes sur lequel `tridentctl` doit fonctionner. Lorsque vous travaillez avec plusieurs environnements Kubernetes, vous devez vous assurer que le `KUBECONFIG` fichier provient correctement.
* Pour réclamer de l'espace en ligne pour des volumes persistants iSCSI, le système d'exploitation sous-jacent du nœud worker peut nécessiter le passage des options de montage vers le volume. Ceci est vrai pour les instances RHEL/Red Hat Enterprise Linux CoreOS (RHCOS), qui nécessitent le `discard` https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["option de montage"^]; assurez-vous que la mise au rebut de mountOption est incluse dans votre^] pour prendre en charge le blocage en ligne jeter[`StorageClass`.
* Si vous avez plusieurs instances de Trident par cluster Kubernetes, Trident ne peut pas communiquer avec d'autres instances et ne peut pas découvrir d'autres volumes qu'elles ont créés. Ce qui entraîne un comportement inattendu et incorrect si plusieurs instances s'exécutent dans un cluster. Il ne doit y avoir qu'une seule instance de Trident par cluster Kubernetes.
* Si des objets basés sur Trident `StorageClass` sont supprimés de Kubernetes alors que Trident est hors ligne, Trident ne supprime pas les classes de stockage correspondantes de sa base de données lorsqu'il est de nouveau en ligne. Vous devez supprimer ces classes de stockage à l'aide de `tridentctl` ou de l'API REST.
* Si un utilisateur supprime un volume persistant provisionné par Trident avant la suppression de la demande de volume persistant correspondante, Trident ne supprime pas automatiquement le volume de sauvegarde. Vous devez supprimer le volume via `tridentctl` ou l'API REST.
* ONTAP ne peut pas provisionner simultanément plusieurs FlexGroup, sauf si l'ensemble d'agrégats est unique pour chaque demande de provisionnement.
* Lorsque vous utilisez Trident sur IPv6, vous devez spécifier `managementLIF` et `dataLIF` dans la définition du backend entre crochets. Par exemple``[fd20:8b1e:b258:2000:f816:3eff:feec:0]``, .
+

NOTE: Vous ne pouvez pas spécifier `dataLIF` sur un système SAN backend ONTAP. Trident détecte toutes les LIFs iSCSI disponibles et les utilise pour établir la session multivoie.

* Si vous utilisez le `solidfire-san` Pilote avec OpenShift 4.5, assurez-vous que les nœuds de travail sous-jacents utilisent MD5 comme algorithme d'authentification CHAP. Les algorithmes CHAP sécurisés conformes à la norme FIPS SHA1, SHA-256 et SHA3-256 sont disponibles avec Element 12.7.




== Trouvez plus d'informations

* https://github.com/NetApp/trident["GitHub pour Trident"^]
* https://netapp.io/persistent-storage-provisioner-for-kubernetes/["Blogs Trident"^]

