---
sidebar: sidebar 
permalink: trident-managing-k8s/uninstall-trident.html 
keywords: uninstall, Trident, methods, operator, tridentctl, helm, downgrade, obliviate, crds, wipeout, downgrade 
summary: 'Vous devez utiliser la même méthode pour désinstaller Trident que celle utilisée pour installer Trident. Si vous avez besoin d"un correctif pour les bugs observés après une mise à niveau, des problèmes de dépendance ou une mise à niveau non réussie ou incomplète, désinstallez Trident et réinstallez la version précédente en suivant les instructions spécifiques à cette version.' 
---
= Désinstaller Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez utiliser la même méthode pour désinstaller Trident que celle utilisée pour installer Trident.

.Description de la tâche
* Si vous avez besoin d'un correctif pour les bogues observés après une mise à niveau, des problèmes de dépendance ou une mise à niveau non réussie ou incomplète, désinstallez Trident et réinstallez la version précédente en suivant les instructions spécifiques à cette mise à niveau link:../earlier-versions.html["version"]. Il s'agit de la seule méthode recommandée pour _rétrograder_ vers une version antérieure.
* Pour faciliter la mise à niveau et la réinstallation, la désinstallation de Trident ne supprime pas les CRD ou les objets associés créés par Trident. Si vous devez supprimer complètement Trident et toutes ses données, reportez-vous à la link:../troubleshooting.html#completely-remove-trident-and-crds["Retirez complètement les Trident et les CRD"].


.Avant de commencer
Si vous désaffectez des clusters Kubernetes, vous devez supprimer toutes les applications qui utilisent des volumes créés par Trident avant de procéder à la désinstallation. Cela permet de s'assurer que les ESV ne sont pas publiées sur les nœuds Kubernetes avant d'être supprimées.



== Déterminez la méthode d'installation d'origine

Vous devez utiliser la même méthode pour désinstaller Trident que celle utilisée pour l'installer. Avant de procéder à la désinstallation, vérifiez la version que vous avez utilisée pour installer Trident à l'origine.

. Utiliser `kubectl get pods -n trident` pour examiner les pods.
+
** S'il n'y a pas de module opérateur, Trident a été installé à l'aide de `tridentctl`.
** S'il existe un module opérateur, Trident a été installé à l'aide de l'opérateur Trident soit manuellement, soit à l'aide de l'assistant.


. S'il y a un module opérateur, utilisez `kubectl describe tproc trident` pour déterminer si Trident a été installé à l'aide de l'assistant.
+
** S'il y a une étiquette Helm, Trident a été installé à l'aide de Helm.
** S'il n'y a pas d'étiquette Helm, Trident a été installé manuellement à l'aide de l'opérateur Trident.






== Désinstallez l'installation d'un opérateur Trident

Vous pouvez désinstaller manuellement l'installation d'un opérateur trident ou à l'aide d'Helm.



=== Désinstallez l'installation manuelle

Si vous avez installé Trident à l'aide de l'opérateur, vous pouvez le désinstaller en effectuant l'une des opérations suivantes :

. **Modifier `TridentOrchestrator` CR et définir l'indicateur de désinstallation** :
+
[listing]
----
kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"uninstall":true}}'
----
+
Lorsque le `uninstall` l'indicateur est défini sur `true`, L'opérateur Trident désinstalle Trident, mais ne supprime pas TridentOrchestrator lui-même. Vous devez nettoyer TridentOrchestrator et en créer un nouveau si vous souhaitez réinstaller Trident.

. **Supprimer `TridentOrchestrator`** : en supprimant la `TridentOrchestrator` CR utilisée pour déployer Trident, vous demandez à l'opérateur de désinstaller Trident. L'opérateur procède à la suppression du `TridentOrchestrator` déploiement et du démonset Trident, en supprimant les pods Trident qu'il avait créés dans le cadre de l'installation.
+
[listing]
----
kubectl delete -f deploy/<bundle.yaml> -n <namespace>
----




=== Désinstallez l'installation d'Helm

Si vous avez installé Trident à l'aide de Helm, vous pouvez le désinstaller en utilisant `helm uninstall`.

[listing]
----
#List the Helm release corresponding to the Trident install.
helm ls -n trident
NAME          NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
trident       trident         1               2021-04-20 00:26:42.417764794 +0000 UTC deployed        trident-operator-21.07.1        21.07.1

#Uninstall Helm release to remove Trident
helm uninstall trident -n trident
release "trident" uninstalled
----


== Désinstallez un `tridentctl` installation

Utilisez la `uninstall` commande dans `tridentctl` pour supprimer toutes les ressources associées à Trident, à l'exception des CRD et des objets associés :

[listing]
----
./tridentctl uninstall -n <namespace>
----