---
sidebar: sidebar 
permalink: trident-managing-k8s/upgrade-tridentctl.html 
keywords: upgrade, trident, methods, operator, tridentctl, helm 
summary: 'Vous pouvez facilement mettre à niveau une installation Trident existante à l"aide de `tridentctl`.' 
---
= Mise à niveau avec tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez facilement mettre à niveau une installation Trident existante à l'aide de `tridentctl`.

.Description de la tâche
La désinstallation et la réinstallation de Trident agit comme une mise à niveau. Lorsque vous désinstallez Trident, la demande de volume persistant et le volume persistant utilisés par le déploiement Trident ne sont pas supprimés. Les volumes persistants déjà provisionnés restent disponibles pendant que Trident est hors ligne et Trident provisionne les volumes pour toutes les demandes de volume persistant créées entre la remise en ligne.

.Avant de commencer
Révision link:upgrade-trident.html#select-an-upgrade-method["Sélectionnez une méthode de mise à niveau"] avant la mise à niveau avec `tridentctl`.

.Étapes
. Exécutez la commande de désinstallation dans `tridentctl` pour supprimer toutes les ressources associées à Trident, à l'exception des CRD et des objets associés.
+
[listing]
----
./tridentctl uninstall -n <namespace>
----
. Réinstallez Trident. Reportez-vous à la link:../trident-get-started/kubernetes-deploy-tridentctl.html["Installez Trident à l'aide de tridentctl"].



IMPORTANT: N'interrompez pas le processus de mise à niveau. Assurez-vous que le programme d'installation s'exécute jusqu'à la fin.
