---
sidebar: sidebar 
permalink: trident-managing-k8s/upgrade-operator-overview.html 
keywords: upgrade, trident, operator, helm, controller, daemonset, node pods, rolling upgrade, zero downtime 
summary: 'Avant d"utiliser l"opérateur Trident pour mettre à niveau Trident, vous devez comprendre les processus en arrière-plan qui se produisent pendant la mise à niveau. Cela inclut les modifications apportées au contrôleur Trident, au pod du contrôleur et aux pods des nœuds, ainsi qu"au jeu de démonstration des nœuds qui activent les mises à jour en continu.' 
---
= Comprendre le workflow de mise à niveau de l'opérateur
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'utiliser l'opérateur Trident pour mettre à niveau Trident, vous devez comprendre les processus en arrière-plan qui se produisent pendant la mise à niveau. Cela inclut les modifications apportées au contrôleur Trident, au pod du contrôleur et aux pods des nœuds, ainsi qu'au jeu de démonstration des nœuds qui activent les mises à jour en continu.



== Gestion des mises à niveau par l'opérateur Trident

L'une des nombreuses link:../trident-get-started/kubernetes-deploy.html["Avantages de l'utilisation de l'opérateur Trident"] à installer et à mettre à niveau Trident est la gestion automatique des objets Trident et Kubernetes sans interrompre les volumes montés existants. De cette façon, Trident peut prendre en charge les mises à niveau sans temps d'indisponibilité, ou link:https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-intro/["_mises à jour en continu_"^]. En particulier, l'opérateur Trident communique avec le cluster Kubernetes pour :

* Supprimez et recréez le déploiement du contrôleur Trident et le nœud DemonSet.
* Remplacez l'afficheur de contrôleur Trident et les pods de nœud Trident par de nouvelles versions.
+
** Si un nœud n'est pas mis à jour, il n'empêche pas la mise à jour des nœuds restants.
** Seuls les nœuds exécutant Trident Node Pod peuvent monter des volumes.





TIP: Pour plus d'informations sur l'architecture Trident sur le cluster Kubernetes, reportez-vous à link:trident-concepts/intro.html#trident-architecture["Architecture Trident"]la .



== Workflow de mise à niveau de l'opérateur

Lorsque vous lancez une mise à niveau avec l'opérateur Trident :

. L'opérateur *Trident* :
+
.. Détecte la version actuellement installée de Trident (version _n_).
.. Mise à jour de tous les objets Kubernetes, y compris les CRD, RBAC et le service Trident.
.. Supprime le déploiement du contrôleur Trident pour la version _n_.
.. Crée le déploiement du contrôleur Trident pour la version _n+1_.


. *Kubernetes* crée le pod du contrôleur Trident pour _n+1_.
. L'opérateur *Trident* :
+
.. Supprime le jeu de démonstration du nœud Trident pour _n_. L'opérateur n'attend pas la fin de Node Pod.
.. Crée le dédéclenchement du nœud Trident pour _n+1_.


. *Kubernetes* crée des pods de nœuds Trident sur les nœuds qui n'exécutent pas Trident Node Pod _n_. Cela permet de garantir qu'il n'y a jamais plus d'un pod de nœuds Trident, quelle que soit la version, sur un nœud.

