---
sidebar: sidebar 
permalink: trident-use/backends.html 
keywords: backends, storage system, anf, cvs for gcp, element, hci, solidfire, ontap, aff, fas, ontap select, configure backends, fsx 
summary: Un back-end définit la relation entre Trident et un système de stockage. Il explique à Trident comment communiquer avec ce système de stockage et comment Trident doit provisionner les volumes à partir de celui-ci. 
---
= Configuration des systèmes back-end
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un back-end définit la relation entre Trident et un système de stockage. Il explique à Trident comment communiquer avec ce système de stockage et comment Trident doit provisionner les volumes à partir de celui-ci.

Trident propose automatiquement des pools de stockage back-end correspondant aux exigences définies par une classe de stockage. Découvrez comment configurer le système back-end pour votre système de stockage.

* link:anf.html["Configurer un back-end Azure NetApp Files"^]
* link:gcnv.html["Configurez un système back-end Google Cloud NetApp volumes"^]
* link:gcp.html["Configurer un Cloud Volumes Service pour le backend de Google Cloud Platform"^]
* link:element.html["Configurer un système NetApp HCI ou SolidFire backend"^]
* link:ontap-nas.html["Configurer un système back-end avec des pilotes NAS ONTAP ou Cloud Volumes ONTAP"^]
* link:ontap-san.html["Configurer un système back-end avec des pilotes ONTAP ou Cloud Volumes ONTAP SAN"^]
* link:trident-fsx.html["Utilisez Trident avec Amazon FSX pour NetApp ONTAP"^]

