---
sidebar: sidebar 
permalink: trident-use/fcp.html 
keywords: storage class, manage storage class, storage classes, kubernetes storage classes, worker node, iscsi, scsi, scsi over fc, fibre channel, fcp, kubernetes clusters, self-healing, healing. 
summary:  
---
= Prise en charge de Fibre Channel (FC)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez désormais utiliser le protocole Fibre Channel (FC) avec Trident pour provisionner et gérer les ressources de stockage sur un système ONTAP.

*SCSI over Fibre Channel (FC) est une fonctionnalité de prévisualisation technique dans la version Trident 24.10.*

Fibre Channel est un protocole largement adopté dans les environnements de stockage d'entreprise en raison de ses performances élevées, de sa fiabilité et de son évolutivité. Il fournit un canal de communication robuste et efficace pour les périphériques de stockage, permettant des transferts de données rapides et sécurisés. En utilisant SCSI over Fibre Channel, vous pouvez exploiter leur infrastructure de stockage SCSI existante tout en bénéficiant des performances élevées et des capacités longue distance de Fibre Channel. Il permet de consolider les ressources de stockage et de créer des réseaux de stockage (SAN) évolutifs et efficaces, capables de gérer d'importants volumes de données à faible latence.

Grâce à la fonctionnalité FC de Trident, vous pouvez effectuer les opérations suivantes : * provisionnement dynamique des ESV à l'aide d'une spécification de déploiement. * Prendre des instantanés de volume et créer un nouveau volume à partir de l'instantané. * Cloner un FC-PVC existant. * Redimensionner un volume déjà déployé.



== Prérequis

Configurez les paramètres réseau et nœud requis pour FC.



=== Paramètres réseau

. Obtenez le WWPN des interfaces cibles. Pour plus d'informations, reportez-vous à la section link:..https://docs.netapp.com/us-en/ontap-cli//network-interface-show.html["interface réseau affiche"^] .
. Procurez-vous le WWPN pour les interfaces sur l'initiateur (hôte).
+
Reportez-vous aux utilitaires correspondants du système d'exploitation hôte.

. Configurer la segmentation sur le commutateur FC à l'aide des WWPN de l'hôte et de la cible.
+
Pour plus d'informations, reportez-vous à la documentation du fournisseur du commutateur Respecive.

+
Pour plus d'informations, reportez-vous à la documentation ONTAP suivante :

+
** https://docs.netapp.com/us-en/ontap/san-config/fibre-channel-fcoe-zoning-concept.html["Présentation de la segmentation Fibre Channel et FCoE"^]
** https://docs.netapp.com/us-en/ontap/san-config/configure-fc-nvme-hosts-ha-pairs-reference.html["Manières de configurer FC  ; hôtes SAN FC-NVMe"^]






=== Préparez le nœud de travail

Tous les nœuds workers du cluster Kubernetes doivent pouvoir monter les volumes provisionnés pour vos pods. Pour préparer les nœuds worker pour FC, vous devez installer les outils requis.

.Installez les outils FC
Installez les outils FC à l'aide des commandes de votre système d'exploitation.

* Lorsque vous utilisez des nœuds workers exécutant RHEL/RedHat CoreOS avec iSCSI PVS, spécifiez le `discard` MounOption dans la classe de stockage pour effectuer la réclamation d'espace en ligne. Reportez-vous à la section https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["Documentation Red Hat"^].


[role="tabbed-block"]
====
.RHEL 8+
--
. Installez les packages système suivants :
+
[listing]
----
sudo yum install -y lsscsi iscsi-initiator-utils device-mapper-multipath
----
. Vérifiez que la version iscsi-initiator-utils est 6.2.0.874-2.el7 ou ultérieure :
+
[listing]
----
rpm -q iscsi-initiator-utils
----
. Activer les chemins d'accès multiples :
+
[listing]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+

NOTE: Bien sûr `etc/multipath.conf` contient `find_multipaths no` sous `defaults`.

. S'assurer que `iscsid` et `multipathd` sont en cours d'exécution :
+
[listing]
----
sudo systemctl enable --now iscsid multipathd
----
. Activer et démarrer `iscsi`:
+
[listing]
----
sudo systemctl enable --now iscsi
----


--
.Ubuntu
--
. Installez les packages système suivants :
+
[listing]
----
sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools
----
. Vérifiez que la version Open-iscsi est 2.0.874-5ubuntu2.10 ou ultérieure (pour bionique) ou 2.0.874-7.1ubuntu6.1 ou ultérieure (pour focaux) :
+
[listing]
----
dpkg -l open-iscsi
----
. Définir la numérisation sur manuelle :
+
[listing]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. Activer les chemins d'accès multiples :
+
[listing]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+

NOTE: Bien sûr `etc/multipath.conf` contient `find_multipaths no` sous `defaults`.

. S'assurer que `open-iscsi` et `multipath-tools` sont activées et en cours d'exécution :
+
[listing]
----
sudo systemctl status multipath-tools
sudo systemctl enable --now open-iscsi.service
sudo systemctl status open-iscsi
----
+

NOTE: Pour Ubuntu 18.04, vous devez découvrir les ports cibles avec `iscsiadm` avant de commencer `open-iscsi` Pour que le démon iSCSI démarre. Vous pouvez également modifier le `iscsi` service à démarrer `iscsid` automatiquement.



--
====


== Créer une configuration back-end

Créez un backend Trident pour le `ontap-san` pilote et `fcp` comme sanType.

Se reporter à :

* link:..trident-use/ontap-san-prep.html["Préparez la configuration du système back-end avec les pilotes SAN ONTAP"]
* link:..trident-use/ontap-san-examples.html["Options et exemples de configuration des SAN ONTAP"^]


.Exemple de configuration back-end avec FC
[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-san
spec:
  version: 1
  backendName: ontap-san-backend
  storageDriverName: ontap-san
  managementLIF: 10.0.0.1
  sanType: fcp
  svm: trident_svm
  credentials:
    name: backend-tbc-ontap-san-secret
----


== Créer une classe de stockage

Pour plus d'informations, se reporter à :

* link:..trident-docker/stor-config.html["Options de configuration du stockage"^]


.Exemple de classe de stockage
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fcp-sc
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san"
  protocol: "fcp"
  storagePool: "aggr1"
allowVolumeExpansion: True
----