---
sidebar: sidebar 
permalink: trident-use/manage-stor-class.html 
keywords: storage class, manage storage class, storage classes, kubernetes storage classes 
summary: Vous pouvez afficher les classes de stockage existantes, définir une classe de stockage par défaut, identifier le back-end de la classe de stockage et supprimer les classes de stockage. 
---
= Gérer les classes de stockage
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher les classes de stockage existantes, définir une classe de stockage par défaut, identifier le back-end de la classe de stockage et supprimer les classes de stockage.



== Afficher les classes de stockage existantes

* Pour afficher les classes de stockage Kubernetes existantes, exécutez la commande suivante :


[listing]
----
kubectl get storageclass
----
* Pour afficher les détails de la classe de stockage Kubernetes, exécutez la commande suivante :


[listing]
----
kubectl get storageclass <storage-class> -o json
----
* Pour afficher les classes de stockage synchronisées de Trident, exécutez la commande suivante :


[listing]
----
tridentctl get storageclass
----
* Pour afficher le détail de la classe de stockage synchronisée de Trident, exécutez la commande suivante :


[listing]
----
tridentctl get storageclass <storage-class> -o json
----


== Définir une classe de stockage par défaut

Kubernetes 1.6 a ajouté la possibilité de définir une classe de stockage par défaut. Cette classe de stockage sera utilisée pour provisionner un volume persistant si un utilisateur ne en spécifie pas une dans une demande de volume persistant.

* Définissez une classe de stockage par défaut en définissant l'annotation `storageclass.kubernetes.io/is-default-class` vrai dans la définition de classe de stockage. Selon la spécification, toute autre valeur ou absence de l'annotation est interprétée comme fausse.
* Vous pouvez configurer une classe de stockage existante comme classe de stockage par défaut à l'aide de la commande suivante :


[listing]
----
kubectl patch storageclass <storage-class-name> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
----
* De même, vous pouvez supprimer l'annotation de classe de stockage par défaut à l'aide de la commande suivante :


[listing]
----
kubectl patch storageclass <storage-class-name> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
----
Il existe également des exemples dans le bundle du programme d'installation de Trident qui incluent cette annotation.


NOTE: Votre cluster ne doit contenir qu'une seule classe de stockage par défaut à la fois. Kubernetes n'empêche pas techniquement d'en avoir plusieurs, mais il se comporte comme s'il n'existe aucune classe de stockage par défaut.



== Identifier le système back-end pour une classe de stockage

Voici un exemple du type de questions que vous pouvez répondre avec le fichier JSON qui `tridentctl` sort pour les objets backend Trident. Cela utilise l' `jq`utilitaire, que vous devrez peut-être installer en premier.

[listing]
----
tridentctl get storageclass -o json | jq  '[.items[] | {storageClass: .Config.name, backends: [.storage]|unique}]'
----


== Supprimer une classe de stockage

Pour supprimer une classe de stockage de Kubernetes, exécutez la commande suivante :

[listing]
----
kubectl delete storageclass <storage-class>
----
`<storage-class>` doit être remplacé par votre classe de stockage.

Tous les volumes persistants créés via cette classe de stockage ne sont pas concernés et Trident continuera de les gérer.


NOTE: Trident applique un espace vide `fsType` pour les volumes qu'il crée. Pour les systèmes back-end iSCSI, il est recommandé d'appliquer la `parameters.fsType` classe de stockage. Vous devez supprimer les classes de stockage existantes et les recréer avec les classes `parameters.fsType` spécifiées.
