---
sidebar: sidebar 
permalink: trident-use/ontap-san.html 
keywords: trident backend, ontap san, ontap-san, ontap-san-economy, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: Découvrez comment configurer un back-end ONTAP avec les pilotes SAN ONTAP. 
---
= Présentation du pilote SAN ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez comment configurer un back-end ONTAP avec les pilotes ONTAP et Cloud Volumes ONTAP SAN.



== Détails du pilote SAN ONTAP

Trident fournit les pilotes de stockage SAN suivants pour communiquer avec le cluster ONTAP. Les modes d'accès pris en charge sont : _ReadWriteOnce_ (RWO), _ReadOnlyMey_ (ROX), _ReadWriteMaly_ (RWX), _ReadWriteOncePod_ (RWOP).

[cols="2, 1, 1, 2, 2"]
|===
| Conducteur | Protocole | Mode Volume | Modes d'accès pris en charge | Systèmes de fichiers pris en charge 


| `ontap-san`  a| 
ISCSI SCSI sur FC
 a| 
Bloc
 a| 
RWO, ROX, RWX, RWOP
 a| 
Pas de système de fichiers, périphérique de bloc brut



| `ontap-san`  a| 
ISCSI SCSI sur FC
 a| 
Système de fichiers
 a| 
RWO, RWOP

ROX et RWX ne sont pas disponibles en mode de volume du système de fichiers.
 a| 
`xfs`, `ext3`, `ext4`



| `ontap-san`  a| 
NVMe/TCP

Reportez-vous à la section <<Autres considérations relatives au NVMe/TCP>>.
 a| 
Bloc
 a| 
RWO, ROX, RWX, RWOP
 a| 
Pas de système de fichiers, périphérique de bloc brut



| `ontap-san`  a| 
NVMe/TCP

Reportez-vous à la section <<Autres considérations relatives au NVMe/TCP>>.
 a| 
Système de fichiers
 a| 
RWO, RWOP

ROX et RWX ne sont pas disponibles en mode de volume du système de fichiers.
 a| 
`xfs`, `ext3`, `ext4`



| `ontap-san-economy`  a| 
ISCSI
 a| 
Bloc
 a| 
RWO, ROX, RWX, RWOP
 a| 
Pas de système de fichiers, périphérique de bloc brut



| `ontap-san-economy`  a| 
ISCSI
 a| 
Système de fichiers
 a| 
RWO, RWOP

ROX et RWX ne sont pas disponibles en mode de volume du système de fichiers.
 a| 
`xfs`, `ext3`, `ext4`

|===
[WARNING]
====
* Utiliser `ontap-san-economy` uniquement si le nombre d'utilisations du volume persistant doit être supérieur à link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["Limites de volume ONTAP prises en charge"^].
* Utiliser `ontap-nas-economy` uniquement si le nombre d'utilisations du volume persistant doit être supérieur à link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["Limites de volume ONTAP prises en charge"^] et le `ontap-san-economy` le pilote ne peut pas être utilisé.
* Ne pas utiliser `ontap-nas-economy` si vous prévoyez d'avoir besoin en termes de protection des données, de reprise sur incident ou de mobilité.
* NetApp ne recommande pas l'utilisation de l'autogrow FlexVol dans tous les pilotes ONTAP, sauf ONTAP-san. Pour contourner ce problème, Trident prend en charge l'utilisation de la réserve Snapshot et adapte les volumes FlexVol en conséquence.


====


== Autorisations utilisateur

Trident s'attend à être exécuté en tant qu'administrateur ONTAP ou SVM, en général avec l'utilisateur du cluster ou un `vsadmin` utilisateur SVM, ou en tant qu' `admin`utilisateur avec un nom différent et le même rôle. Pour les déploiements Amazon FSX pour NetApp ONTAP, Trident prévoit d'être exécuté en tant qu'administrateur ONTAP ou SVM, en utilisant l'utilisateur du cluster `fsxadmin` ou un `vsadmin` utilisateur SVM, ou un utilisateur avec un nom différent ayant le même rôle.  `fsxadmin`L'utilisateur est un remplaçant limité pour l'utilisateur admin du cluster.


NOTE: Si vous utilisez le `limitAggregateUsage` paramètre, les autorisations d'administration du cluster sont requises. Lors de l'utilisation d'Amazon FSX for NetApp ONTAP avec Trident, le `limitAggregateUsage` paramètre ne fonctionnera pas avec les `vsadmin` comptes d'utilisateur et `fsxadmin`. L'opération de configuration échoue si vous spécifiez ce paramètre.

S'il est possible de créer au sein de ONTAP un rôle plus restrictif qu'un pilote Trident peut utiliser, nous ne le recommandons pas. La plupart des nouvelles versions de Trident appellent des API supplémentaires qui devront être prises en compte, ce qui complique les mises à niveau et risque d'erreurs.



== Autres considérations relatives au NVMe/TCP

Trident prend en charge le protocole NVMe (non-volatile Memory Express) avec le `ontap-san` pilote, notamment :

* IPv6
* Copies Snapshot et clones de volumes NVMe
* Redimensionnement d'un volume NVMe
* Importation d'un volume NVMe créé en dehors de Trident afin que son cycle de vie puisse être géré par Trident
* Chemins d'accès multiples natifs NVMe
* Arrêt normal ou sans gracieuse des nœuds K8s (24.06)


Trident ne prend pas en charge :

* DH-HMAC-CHAP pris en charge nativement par NVMe
* Chemins d'accès multiples du mappeur de périphériques (DM)
* Cryptage LUKS



NOTE: NVMe est pris en charge uniquement avec les API REST ONTAP et n'est pas pris en charge avec ONTAPI (ZAPI).
