---
sidebar: sidebar 
permalink: trident-use/trident-fsx-install-trident.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident add-on, Trident EKS add-on, Trident AWS EKS add-on 
summary: 'Avec Trident avec Amazon FSX pour NetApp ONTAP, vous avez l"assurance que vos clusters Kubernetes s"exécutant dans Amazon Elastic Kubernetes Service (EKS) peuvent provisionner des volumes persistants de bloc et de fichier soutenus par ONTAP.' 
---
= Installation de Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident rationalise la gestion du stockage Amazon FSX for NetApp ONTAP dans Kubernetes pour que vos développeurs et administrateurs puissent donner la priorité au déploiement d'applications.

Vous pouvez installer Trident à l'aide de l'une des méthodes suivantes :

* Gouvernail
* Module complémentaire EKS


Si vous souhaitez utiliser la fonctionnalité snapshot, installez le module complémentaire CSI snapshot Controller. Pour plus d'informations, reportez-vous à la section link:https://docs.aws.amazon.com/eks/latest/userguide/csi-snapshot-controller.html["Activer la fonctionnalité snapshot pour les volumes CSI"^] .



== Installez Trident via Helm

. Téléchargez le programme d'installation de Trident
+
Le programme d'installation de Trident contient tout ce dont vous avez besoin pour déployer l'opérateur Trident et installer Trident. Téléchargez et extrayez la dernière version du programme d'installation de Trident à partir de la section Ressources sur GitHub.

+
[source, console]
----
wget https://github.com/NetApp/trident/releases/download/v25.02.0/trident-installer-25.02.0.tar.gz
tar -xf trident-installer-25.02.0.tar.gz
cd trident-installer
----
. Définissez les valeurs des indicateurs *cloud Provider* et *cloud Identity* à l'aide des variables d'environnement suivantes :
+
L'exemple suivant installe Trident et définit l' `cloud-provider`indicateur sur `$CP`, et `cloud-identity` sur `$CI`:

+
[source, console]
----
helm install trident trident-operator-100.2502.0.tgz \
--set cloudProvider="AWS" \
--set cloudIdentity="'eks.amazonaws.com/role-arn: arn:aws:iam::<accountID>:role/<AmazonEKS_FSxN_CSI_DriverRole>'" \
--namespace trident \
--create-namespace
----
+
Vous pouvez utiliser `helm list` la commande pour consulter les détails de l'installation tels que le nom, l'espace de noms, le graphique, l'état, la version de l'application et le numéro de révision.

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2502.0    25.02.0
----




== Installez Trident via le module complémentaire EKS

Le module complémentaire Trident EKS inclut les derniers correctifs de sécurité et de bogues, et est validé par AWS pour une utilisation avec Amazon EKS. Le module complémentaire EKS vous permet de vous assurer de manière cohérente que vos clusters Amazon EKS sont sécurisés et stables et de réduire la quantité de travail à effectuer pour installer, configurer et mettre à jour des modules complémentaires.



=== Prérequis

Vérifiez les points suivants avant de configurer le module complémentaire Trident pour AWS EKS :

* Un compte de cluster Amazon EKS avec abonnement complémentaire
* Autorisations AWS sur AWS Marketplace :
`"aws-marketplace:ViewSubscriptions",
"aws-marketplace:Subscribe",
"aws-marketplace:Unsubscribe`
* Type ami : Amazon Linux 2 (AL2_x86_64) ou Amazon Linux 2 Arm (AL2_ARM_64)
* Type de nœud : AMD ou ARM
* Un système de fichiers Amazon FSX pour NetApp ONTAP




=== Activez le module complémentaire Trident pour AWS

[role="tabbed-block"]
====
.eksctl
--
L'exemple de commande suivant installe le module complémentaire Trident EKS :

[source, console]
----
eksctl create addon --name netapp_trident-operator --cluster <cluster_name> \
--service-account-role-arn arn:aws:iam::<account_id>:role/<role_name> --force
----
--
.Console de gestion
--
. Ouvrez la console Amazon EKS à l'adresse https://console.aws.amazon.com/eks/home#/clusters[].
. Dans le volet de navigation de gauche, sélectionnez *clusters*.
. Sélectionnez le nom du cluster pour lequel vous souhaitez configurer le module complémentaire NetApp Trident CSI.
. Sélectionnez *Compléments*, puis *obtenir plus de modules complémentaires*.
. Sur la page *Select add-ons*, procédez comme suit :
+
.. Dans la section EKS-addons du Marketplace AWS, cochez la case *Trident by NetApp*.
.. Sélectionnez *Suivant*.


. Sur la page *configurer les compléments sélectionnés*, procédez comme suit :
+
.. Sélectionnez la *version* que vous souhaitez utiliser.
.. Pour *Sélectionner le rôle IAM*, laisser à *non défini*.
.. Suivez le schéma de configuration *Add-on* et définissez le paramètre configurationValues dans la section *Configuration Values* sur le fil de rôle que vous avez créé à l'étape précédente (la valeur doit être au format suivant : `eks.amazonaws.com/role-arn: arn:aws:iam::464262061435:role/AmazonEKS_FSXN_CSI_DriverRole`). Si vous sélectionnez remplacer pour la méthode de résolution des conflits, un ou plusieurs des paramètres du module complémentaire existant peuvent être remplacés par les paramètres du module complémentaire Amazon EKS. Si vous n'activez pas cette option et qu'il y a un conflit avec vos paramètres existants, l'opération échoue. Vous pouvez utiliser le message d'erreur qui en résulte pour résoudre le conflit. Avant de sélectionner cette option, assurez-vous que le module complémentaire Amazon EKS ne gère pas les paramètres que vous devez gérer vous-même.


. Choisissez *Suivant*.
. Sur la page *consulter et ajouter*, choisissez *Créer*.
+
Une fois l'installation du module complémentaire terminée, le module complémentaire installé s'affiche.



--
.CLI AWS
--
. Créez le `add-on.json` fichier :
+
[source, JSON]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v24.10.0-eksbuild.1",
  "serviceAccountRoleArn": "<role ARN>",
  "configurationValues": {
    "cloudIdentity": "'cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
    "cloudProvider": "AWS"
  }
}
----
+

NOTE: Remplacer `<role ARN>` par l'ARN du rôle créé à l'étape précédente.

. Installez le module complémentaire Trident EKS.
+
[source, console]
----
aws eks create-addon --cli-input-json file://add-on.json
----


--
====


=== Mettez à jour le module complémentaire Trident EKS

[role="tabbed-block"]
====
.eksctl
--
* Vérifiez la version actuelle de votre module complémentaire FSxN Trident CSI. Remplacez `my-cluster` par le nom de votre cluster.
+
[source, console]
----
eksctl get addon --name netapp_trident-operator --cluster my-cluster
----
+
*Exemple de sortie :*



[listing]
----
NAME                        VERSION             STATUS    ISSUES    IAMROLE    UPDATE AVAILABLE    CONFIGURATION VALUES
netapp_trident-operator    v24.10.0-eksbuild.1    ACTIVE    0       {"cloudIdentity":"'eks.amazonaws.com/role-arn: arn:aws:iam::139763910815:role/AmazonEKS_FSXN_CSI_DriverRole'"}
----
* Mettez à jour le complément à la version renvoyée sous MISE À JOUR DISPONIBLE dans la sortie de l'étape précédente.
+
[source, console]
----
eksctl update addon --name netapp_trident-operator --version v24.10.0-eksbuild.1 --cluster my-cluster --force
----


Si vous supprimez l' `--force` option et que l'un des paramètres du module complémentaire Amazon EKS entre en conflit avec vos paramètres existants, la mise à jour du module complémentaire Amazon EKS échoue ; un message d'erreur s'affiche pour vous aider à résoudre le conflit. Avant de spécifier cette option, assurez-vous que le module complémentaire Amazon EKS ne gère pas les paramètres que vous devez gérer, car ces paramètres sont remplacés par cette option. Pour plus d'informations sur les autres options de ce paramètre, reportez-vous à la section link:https://eksctl.io/usage/addons/["Addons"]. Pour plus d'informations sur la gestion de terrain Amazon EKS Kubernetes, reportez-vous à la section link:https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-field-management.html["Gestion de terrain Kubernetes"].

--
.Console de gestion
--
. Ouvrez la console Amazon EKS https://console.aws.amazon.com/eks/home#/clusters[].
. Dans le volet de navigation de gauche, sélectionnez *clusters*.
. Sélectionnez le nom du cluster pour lequel vous souhaitez mettre à jour le module complémentaire NetApp Trident CSI.
. Sélectionnez l'onglet *Compléments*.
. Sélectionnez *Trident by NetApp*, puis *Edit*.
. Sur la page *configurer Trident par NetApp*, procédez comme suit :
+
.. Sélectionnez la *version* que vous souhaitez utiliser.
.. Développez les *Paramètres de configuration facultatifs* et modifiez-les si nécessaire.
.. Sélectionnez *Enregistrer les modifications*.




--
.CLI AWS
--
L'exemple suivant met à jour le module complémentaire EKS :

[source, console]
----
aws eks update-addon --cluster-name my-cluster netapp_trident-operator vpc-cni --addon-version v24.10.0-eksbuild.1 \
    --service-account-role-arn <role-ARN> --configuration-values '{}' --resolve-conflicts --preserve
----
--
====


=== Désinstallez/supprimez le module complémentaire Trident EKS

Vous avez deux options pour supprimer un module complémentaire Amazon EKS :

* *Préserver le logiciel complémentaire sur votre cluster* – cette option supprime la gestion Amazon EKS de tous les paramètres. Il supprime également la possibilité pour Amazon EKS de vous informer des mises à jour et de mettre à jour automatiquement le module complémentaire Amazon EKS après avoir lancé une mise à jour. Cependant, il conserve le logiciel complémentaire sur votre cluster. Cette option fait du complément une installation auto-gérée, plutôt qu'un module complémentaire Amazon EKS. Avec cette option, vous n'avez plus à subir de temps d'indisponibilité. Conservez `--preserve` l'option dans la commande pour conserver le complément.
* *Supprimer entièrement le logiciel complémentaire de votre cluster* – NetApp vous recommande de supprimer le module complémentaire Amazon EKS de votre cluster uniquement s'il n'y a pas de ressources qui en dépendent sur votre cluster. Supprimez l' `--preserve` option de la `delete` commande pour supprimer le complément.



NOTE: Si le complément est associé à un compte IAM, le compte IAM n'est pas supprimé.

[role="tabbed-block"]
====
.eksctl
--
La commande suivante désinstalle le module complémentaire Trident EKS :

[source, console]
----
eksctl delete addon --cluster K8s-arm --name netapp_trident-operator
----
--
.Console de gestion
--
. Ouvrez la console Amazon EKS à l'adresse https://console.aws.amazon.com/eks/home#/clusters[].
. Dans le volet de navigation de gauche, sélectionnez *clusters*.
. Sélectionnez le nom du cluster pour lequel vous souhaitez supprimer le module complémentaire NetApp Trident CSI.
. Sélectionnez l'onglet *Compléments*, puis sélectionnez *Trident by NetApp*.*
. Sélectionnez *Supprimer*.
. Dans la boîte de dialogue *Remove netapp_trident-operator confirmation*, procédez comme suit :
+
.. Si vous souhaitez qu'Amazon EKS cesse de gérer les paramètres du module complémentaire, sélectionnez *préserver sur le cluster*. Procédez ainsi si vous souhaitez conserver l'extension logicielle sur votre cluster afin de pouvoir gérer tous les paramètres du module complémentaire vous-même.
.. Entrez *netapp_trident-operator*.
.. Sélectionnez *Supprimer*.




--
.CLI AWS
--
Remplacez `my-cluster` par le nom de votre cluster, puis exécutez la commande suivante.

[source, console]
----
aws eks delete-addon --cluster-name my-cluster --addon-name netapp_trident-operator --preserve
----
--
====