---
sidebar: sidebar 
permalink: trident-use/vol-provision.html 
keywords: volumes, pvc, pv, persistentvolume, persistentvolumeclaim, mount, pod, provision 
summary: 'Créez un volume persistant et une demande de volume persistant qui utilisent la classe de stockage Kubernetes configurée pour demander l"accès au volume persistant. Vous pouvez ensuite monter le volume persistant sur un pod.' 
---
= Provisionner un volume
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Créez une demande de volume persistant qui utilise la classe de stockage Kubernetes configurée pour demander l'accès au volume persistant. Vous pouvez ensuite monter le volume persistant sur un pod.



== Présentation

Une https://kubernetes.io/docs/concepts/storage/persistent-volumes["_PersistentVolumeClaim_"^] demande de volume persistant est une demande d'accès au volume persistant sur le cluster.

Le PVC peut être configuré pour demander un stockage d'une certaine taille ou d'un certain mode d'accès. À l'aide de la classe de stockage associée, l'administrateur du cluster peut contrôler plus que la taille du volume persistant et le mode d'accès, tels que les performances ou le niveau de service.

Une fois la demande de volume créée, vous pouvez la monter dans un pod.



== Créer la PVC

.Étapes
. Créer la PVC.
+
[listing]
----
kubectl create -f pvc.yaml
----
. Vérifiez l'état de la demande de volume persistant.
+
[listing]
----
kubectl get pvc
----


[listing]
----
NAME        STATUS  VOLUME     CAPACITY   ACCESS MODES  STORAGECLASS AGE
pvc-storage Bound   pv-name    1Gi        RWO                  5m
----
. Montez le volume dans un pod.
+
[listing]
----
kubectl create -f pv-pod.yaml
----
+

NOTE: Vous pouvez surveiller la progression à l'aide de `kubectl get pod --watch`.

. Vérifiez que le volume est monté sur `/my/mount/path`.
+
[listing]
----
kubectl exec -it task-pv-pod -- df -h /my/mount/path
----
. Vous pouvez maintenant supprimer le Pod. L'application Pod n'existera plus, mais le volume restera.
+
[listing]
----
kubectl delete pod pv-pod
----




=== Exemples de manifestes

.Exemples de manifestes de demande de volume persistant
[%collapsible]
====
Ces exemples présentent les options de configuration de base de la PVC.

.PVC avec accès RWO
Cet exemple montre une demande de volume persistant de base avec accès RWO associée à une classe de stockage nommée `basic-csi`.

[listing]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----
.PVC avec NVMe/TCP
Cet exemple présente une demande de volume persistant de base pour NVMe/TCP avec accès RWO associée à une classe de stockage nommée `protection-gold`.

[listing]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
name: pvc-san-nvme
spec:
accessModes:
  - ReadWriteOnce
resources:
  requests:
    storage: 300Mi
storageClassName: protection-gold
----
====
.Échantillons de manifeste de pod
[%collapsible]
====
Ces exemples présentent les configurations de base pour fixer la demande de volume persistant à un pod.

.Configuration de base
[listing]
----
kind: Pod
apiVersion: v1
metadata:
  name: pv-pod
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
       claimName: pvc-storage
  containers:
    - name: pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/my/mount/path"
          name: storage
----
.Configuration NVMe/TCP de base
[listing]
----
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
spec:
  volumes:
    - name: basic-pvc
      persistentVolumeClaim:
        claimName: pvc-san-nvme
  containers:
    - name: task-pv-container
      image: nginx
      volumeMounts:
        - mountPath: "/my/mount/path"
          name: basic-pvc
----
====
Reportez-vous link:../trident-reference/objects.html["Kubernetes et objets Trident"]à pour plus de détails sur l'interaction des classes de stockage avec les `PersistentVolumeClaim` paramètres et pour le contrôle de la manière dont Trident provisionne les volumes.
