---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy.html 
keywords: deploy, trident, methods, operator, tridentctl, helm, attributes, customize, tridentorchestrator, smb, windows 
summary: 'L"opérateur Trident vous permet de personnaliser la manière dont Trident est installé à l"aide des attributs de la `TridentOrchestrator` spécification.' 
---
= Personnalisez l'installation de l'opérateur Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'opérateur Trident vous permet de personnaliser l'installation Trident à l'aide des attributs de la `TridentOrchestrator` spécification. Si vous souhaitez personnaliser l'installation au-delà des `TridentOrchestrator` arguments autorisés, envisagez d'utiliser `tridentctl` pour générer des manifestes YAML personnalisés à modifier si nécessaire.



== Présentation des pods de contrôleur et des nœuds

Trident s'exécute comme un seul pod de contrôleur, plus un pod de nœud sur chaque nœud worker du cluster. Le pod de nœud doit s'exécuter sur n'importe quel hôte sur lequel vous souhaitez potentiellement monter un volume Trident.

Kubernetes link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["sélecteurs de nœuds"^] et link:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/["tolérances et rejets"^] sont utilisés pour contraindre un pod à s'exécuter sur un nœud spécifique ou préféré. En utilisant le « ControllerPlugin » et `NodePlugin`, vous pouvez spécifier des contraintes et des remplacements.

* Le plug-in du contrôleur gère le provisionnement et la gestion des volumes, tels que les snapshots et le redimensionnement.
* Le plug-in du nœud permet d'attacher le stockage au nœud.




== Options de configuration


WARNING: `spec.namespace` Est spécifié dans pour indiquer l'espace de noms dans `TridentOrchestrator` lequel Trident est installé. Ce paramètre *ne peut pas être mis à jour après l'installation de Trident*. Si vous essayez de le faire, l' `TridentOrchestrator`état passe à `Failed`. Trident n'est pas destiné à être migré entre les espaces de noms.

Ce tableau est plus détaillé `TridentOrchestrator` attributs.

[cols="1,2,1"]
|===
| Paramètre | Description | Valeur par défaut 


| `namespace` | Espace de noms pour installer Trident dans | `"default"` 


| `debug` | Activer le débogage pour Trident | `false` 


| `enableForceDetach` | `ontap-san`, `ontap-san-economy`, , `ontap-nas` et `ontap-nas-economy` uniquement. Fonctionne avec Kubernetes non-Grass Node Shutdown (NGN) pour autoriser les administrateurs du cluster à migrer en toute sécurité les workloads avec des volumes montés vers de nouveaux nœuds en cas de problème. | `false` 


| `windows` | Réglage sur `true` Active l'installation sur les nœuds de travail Windows. | `false` 


| `cloudProvider`  a| 
Défini sur `"Azure"` lors de l'utilisation d'identités gérées ou d'une identité cloud sur un cluster AKS. Défini sur `"AWS"` lors de l'utilisation d'une identité de cloud sur un cluster EKS. Défini sur `"GCP"` lors de l'utilisation d'une identité de nuage sur un cluster GKE.
| `""` 


| `cloudIdentity`  a| 
Défini sur l'identité de la charge de travail (« Azure.Workload.Identity/client-ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxx ») lors de l'utilisation de l'identité cloud sur un cluster AKS. Défini sur le rôle IAM AWS (« eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/Trident-role ») lors de l'utilisation de l'identité cloud sur un cluster EKS. Défini sur l'identité cloud (« iam.gke.io/gcp-service-account: xxxx@mygcpproject.iam.gserviceaccount.com ») lors de l'utilisation de l'identité cloud sur un cluster GKE.
| `""` 


| `IPv6` | Installez Trident sur IPv6 | faux 


| `k8sTimeout`  a| 
Délai d'expiration pour les opérations Kubernetes.


NOTE: Le `k8sTimeout` le paramètre s'applique uniquement à l'installation de Trident .
| `180sec` 


| `silenceAutosupport` | N'envoyez pas de packs AutoSupport à NetApp
automatiquement | `false` 


| `autosupportImage` | Image conteneur pour la télémétrie AutoSupport | `"netapp/trident-autosupport:25.06"` 


| `autosupportProxy` | Adresse/port d'un proxy pour l'envoi de AutoSupport
Télémétrie | `"http://proxy.example.com:8888"` 


| `uninstall` | Indicateur utilisé pour désinstaller Trident | `false` 


| `logFormat` | Format de journalisation Trident à utiliser [TEXT,json] | `"text"` 


| `tridentImage` | Image Trident à installer | `"netapp/trident:25.06"` 


| `imageRegistry` | Chemin d'accès au registre interne, du format
`<registry FQDN>[:port][/subpath]` | `"registry.k8s.io"` 


| `kubeletDir` | Chemin d'accès au répertoire kubelet de l'hôte | `"/var/lib/kubelet"` 


| `wipeout` | Liste des ressources à supprimer pour effectuer une suppression complète de Trident |  


| `imagePullSecrets` | Secrets pour extraire des images d'un registre interne |  


| `imagePullPolicy` | Définit la stratégie de collecte d'image pour l'opérateur Trident. Les valeurs valides sont :
`Always` pour toujours tirer l'image.
`IfNotPresent` pour extraire l'image uniquement s'il n'existe pas déjà sur le nœud.
`Never` pour ne jamais tirer l'image. | `IfNotPresent` 


| `controllerPluginNodeSelector` | Sélecteurs de nœuds supplémentaires pour les pods.	Suit le même format que `pod.spec.nodeSelector`. | Pas de valeur par défaut ; facultatif 


| `controllerPluginTolerations` | Remplace les tolérances Kubernetes pour les pods. Suit le même format que `pod.spec.Tolerations`. | Pas de valeur par défaut ; facultatif 


| `nodePluginNodeSelector` | Sélecteurs de nœuds supplémentaires pour les pods. Suit le même format que `pod.spec.nodeSelector`. | Pas de valeur par défaut ; facultatif 


| `nodePluginTolerations` | Remplace les tolérances Kubernetes pour les pods. Suit le même format que `pod.spec.Tolerations`. | Pas de valeur par défaut ; facultatif 


| `nodePrep`  a| 
Permet à Trident de préparer les nœuds du cluster Kubernetes à gérer les volumes à l'aide du protocole de stockage de données spécifié. *Actuellement, `iscsi` est la seule valeur prise en charge.*


NOTE: À partir d'OpenShift 4.19, la version minimale de Trident prise en charge pour cette fonctionnalité est 25.06.1.
|  
|===

NOTE: Pour plus d'informations sur le formatage des paramètres du pod, reportez-vous à la section link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["Attribution de pods aux nœuds"^].



=== Détails sur le détachement forcé

Forcer le détachement est disponible pour `ontap-san`, `ontap-san-economy`, `onatp-nas` et `onatp-nas-economy` uniquement. Avant d'activer le détachement forcé, l'arrêt non autorisé des nœuds (NGN) doit être activé sur le cluster Kubernetes. LES NGN sont activés par défaut pour Kubernetes 1.28 et les versions ultérieures. Pour plus d'informations, reportez-vous link:https://kubernetes.io/docs/concepts/cluster-administration/node-shutdown/#non-graceful-node-shutdown["Kubernetes : arrêt du nœud sans interruption"^]à .


NOTE: Lorsque vous utilisez le `ontap-nas` pilote ou `ontap-nas-economy`, vous devez définir le `autoExportPolicy` paramètre de la configuration back-end sur `true` afin que Trident puisse restreindre l'accès au nœud Kubernetes avec la valeur taint appliquée à l'aide des règles d'exportation gérées.


WARNING: Comme Trident repose sur les NGN Kubernetes, ne supprimez pas les `out-of-service` nœuds défectueux avant que toutes les charges de travail non tolérables ne soient replanifiées. L'application ou la suppression imprudemment de cet outil peut compromettre la protection des données back-end.

Lorsque l'administrateur du cluster Kubernetes a appliqué le `node.kubernetes.io/out-of-service=nodeshutdown:NoExecute` taint au nœud et `enableForceDetach` est défini sur `true`, Trident détermine l'état du nœud et :

. Cessez l'accès aux E/S back-end pour les volumes montés sur ce nœud.
. Marquer l'objet de nœud Trident comme `dirty` (non sécurisé pour les nouvelles publications).
+

NOTE: Le contrôleur Trident rejette les nouvelles demandes de volume publiées jusqu'à ce que le nœud soit de nouveau qualifié (après avoir été marqué comme `dirty`) par le pod de nœud Trident. Toutes les charges de travail planifiées avec une demande de volume persistant montée (même lorsque le nœud du cluster est sain et prêt) ne seront pas acceptées tant que Trident ne pourra pas vérifier le nœud `clean` (compatibilité pour les nouvelles publications).



Lorsque l'intégrité du nœud est restaurée et que la taint est supprimée, Trident :

. Identifiez et nettoyez les chemins publiés obsolètes sur le nœud.
. Si le nœud est dans un `cleanable` état (le taint hors service a été supprimé et le nœud est à `Ready` l'état) et que tous les chemins obsolètes et publiés sont propres, Trident reprépare le nœud en tant que et autorise la publication de `clean` nouveaux volumes sur le nœud.




== Exemples de configurations

Vous pouvez utiliser les attributs dans <<Options de configuration>> lors de la définition `TridentOrchestrator` pour personnaliser votre installation.

.Configuration personnalisée de base
[%collapsible]
====
Cet exemple, créé après l'exécution de la `cat deploy/crds/tridentorchestrator_cr_imagepullsecrets.yaml` commande, représente une installation personnalisée de base :

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullSecrets:
  - thisisasecret
----
====
.Sélecteurs de nœuds
[%collapsible]
====
Cet exemple installe Trident avec des sélecteurs de nœuds.

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  controllerPluginNodeSelector:
    nodetype: master
  nodePluginNodeSelector:
    storage: netapp
----
====
.Nœuds worker Windows
[%collapsible]
====
Cet exemple, créé après l'exécution de la `cat deploy/crds/tridentorchestrator_cr.yaml` commande, installe Trident sur un noeud de travail Windows.

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  windows: true
----
====
.Identités gérées sur un cluster AKS
[%collapsible]
====
Cet exemple installe Trident pour activer les identités gérées sur un cluster AKS.

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  cloudProvider: "Azure"
----
====
.Identité cloud sur un cluster AKS
[%collapsible]
====
Cet exemple installe Trident pour une utilisation avec une identité de cloud sur un cluster AKS.

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  cloudProvider: "Azure"
  cloudIdentity: 'azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx'

----
====
.Identité cloud sur un cluster EKS
[%collapsible]
====
Cet exemple installe Trident pour une utilisation avec une identité de cloud sur un cluster AKS.

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  cloudProvider: "AWS"
  cloudIdentity: "'eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/trident-role'"
----
====
.Identité cloud pour GKE
[%collapsible]
====
Cet exemple installe Trident pour une utilisation avec une identité de cloud sur un cluster GKE.

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-gcp-gcnv
spec:
  version: 1
  storageDriverName: google-cloud-netapp-volumes
  projectNumber: '012345678901'
  network: gcnv-network
  location: us-west2
  serviceLevel: Premium
  storagePool: pool-premium1
----
====