= Annotation de délai d'expiration du moteur de transfert de données
:allow-uri-read: 




== Annotation de délai d'expiration du moteur de transfert de données

Lors des opérations de sauvegarde et de restauration, vous pouvez utiliser l'annotation  `protect.trident.netapp.io/data-mover-timeout-sec` Pour configurer le délai d'expiration des opérations de déplacement de données. Cette annotation spécifie le délai maximal, en secondes, pendant lequel un moteur de déplacement de données doit attendre la fin d'une opération spécifique avant d'être interrompu. Elle est particulièrement utile lorsque des problèmes réseau ou d'autres facteurs peuvent entraîner le blocage des opérations de déplacement de données. Elle permet de détecter et de gérer les opérations interrompues, plutôt que de définir un délai d'expiration général pour l'ensemble du processus. Par exemple, si la restauration des données du volume ne progresse pas en raison de problèmes réseau, l'opération expirera selon la durée spécifiée.

Vous pouvez utiliser cette annotation dans votre fichier YAML comme indiqué ci-dessous :

[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: BackupRestore
metadata:
  name: bkp-restore-kopia
  namespace: trident-protect
  annotations: # Optional annotations to configure data movement timeout
    protect.trident.netapp.io/data-mover-timeout-sec: "2"
spec:
  appVaultRef: appvault-name
  appArchivePath: my-backup-path
  namespaceMapping: [{"source": "my-source-namespace", "destination": "my-destination-namespace"}]
  storageClassMapping:
    destination: "${destinationStorageClass}"
    source: "${sourceStorageClass}"
----
Dans cet exemple, l'annotation échoue  `BackupRestore` opération si aucune progression ne se produit dans les 2 secondes de l'opération de restauration.


NOTE: Si la valeur d'annotation est inférieure ou égale à 0, l'opération échouera immédiatement.
