---
sidebar: sidebar 
permalink: trident-get-started/requirements.html 
keywords: trident requirements, supported front ends, supported backends, kubernetes cluster, cluster requirements, version requirements, supported versions, host configuration, host os, system configuration, host operating system, fsx, ports, csi, images, orchestrators, storage systems, feature, kubernetes 
summary: 'Avant d"installer Trident, vous devez vérifier la configuration système requise. Il se peut que les systèmes back-end spécifiques présentent des exigences supplémentaires.' 
---
= De formation
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'installer Trident, vous devez vérifier la configuration système requise. Il se peut que les systèmes back-end spécifiques présentent des exigences supplémentaires.



== Informations critiques sur Trident

*Vous devez lire les informations critiques suivantes sur Trident.*

.<strong> informations sur le Trident </strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.33 est désormais pris en charge dans Trident. Mise à niveau de Trident avant la mise à niveau de Kubernetes.
* Trident applique strictement l'utilisation de la configuration de chemins d'accès multiples dans les environnements SAN, avec une valeur recommandée de `find_multipaths: no` dans le fichier multipath.conf.
+
Utilisation d'une configuration sans chemins d'accès multiples ou de l'utilisation de `find_multipaths: yes` ou `find_multipaths: smart` la valeur du fichier multipath.conf entraînera des échecs de montage. Trident a recommandé l'utilisation de `find_multipaths: no` depuis la version 21.07.



=====
====


== Systèmes front-end (orchestrateurs) pris en charge

Trident prend en charge plusieurs moteurs de mise en conteneurs et orchestrateurs, notamment :

* Anthos sur site (VMware) et Anthos sur bare Metal 1.16
* Kubernetes 1.27 - 1.33
* OpenShift 4.14 - 4.18
* Rancher Kubernetes Engine 2 (RKE2) v1.27.x - 1.33.x



NOTE: _Alors que Trident est pris en charge sur les versions 1.27.x à 1.33.x de Rancher Kubernetes Engine 2 (RKE2), Trident est actuellement qualifié uniquement sur RKE2 v1.28.5+rke2r1._

Trident fonctionne également avec de nombreuses autres offres Kubernetes entièrement gérées et autogérées, notamment Google Kubernetes Engine (GKE), Amazon Elastic Kubernetes Services (EKS), Azure Kubernetes Service (AKS), Mirantis Kubernetes Engine (MKE) et le portefeuille VMware Tanzu.

Trident et ONTAP peuvent être utilisés comme fournisseur de stockage pour link:https://kubevirt.io/["KubeVirt"].


WARNING: Avant de mettre à niveau un cluster Kubernetes de la version 1.25 vers la version 1.26 ou ultérieure sur link:../trident-managing-k8s/upgrade-operator.html#upgrade-a-helm-installation["Mettre à niveau une installation Helm"]lequelTrident est installé, reportez-vous à la section .



== Systèmes back-end pris en charge (stockage)

Pour utiliser Trident, vous avez besoin d'un ou plusieurs des systèmes back-end pris en charge suivants :

* Amazon FSX pour NetApp ONTAP
* Azure NetApp Files
* Cloud Volumes ONTAP
* Google Cloud NetApp volumes
* Baie SAN 100 % Flash (ASA) de NetApp
* Versions de cluster FAS, AFF ou ASA r2 (iSCSI et NVMe/TCP) sur site sous le support limité de NetApp. Voir link:https://mysupport.netapp.com/site/info/version-support["Prise en charge des versions logicielles"].
* Logiciel NetApp HCI/Element 11 ou version ultérieure




== Prise en charge de Trident pour KubeVirt et OpenShift Virtualization

.Pilotes de stockage pris en charge :
Trident prend en charge les pilotes ONTAP suivants pour KubeVirt et OpenShift Virtualization :

* ontap-nas
* ONTAP-nas-économie
* san ONTAP (iSCSI, FCP, NVMe over TCP)
* ONTAP-san-Economy (iSCSI uniquement)


.Points à prendre en compte :
* Mettez à jour la classe de stockage pour avoir le `fsType` paramètre (par exemple : `fsType: "ext4"`) dans l'environnement OpenShift Virtualization. Si nécessaire, définissez le mode de volume pour bloquer explicitement à l'aide du `volumeMode=Block` paramètre dans `dataVolumeTemplates` pour avertir CDI de créer des volumes de données de bloc.
* Mode d'accès _RWX pour les pilotes de stockage en mode bloc_ : les pilotes ONTAP-san (iSCSI, NVMe/TCP, FC) et ONTAP-san-Economy (iSCSI) sont pris en charge uniquement avec les pilotes « volumeMode : bloc » (périphérique brut). Pour ces pilotes, le `fstype` paramètre ne peut pas être utilisé car les volumes sont fournis en mode périphérique brut.
* Pour les flux de travail de migration dynamique où le mode d'accès RWX est requis, ces combinaisons sont prises en charge :
+
** NFS + `volumeMode=Filesystem`
** ISCSI + `volumeMode=Block` (périphérique brut)
** NVMe/TCP + `volumeMode=Block` (périphérique brut)
** FC + `volumeMode=Block` (périphérique brut)






== Configuration requise

Le tableau ci-dessous résume les fonctionnalités disponibles dans cette version d'Trident et les versions de Kubernetes qu'il prend en charge.

[cols="3"]
|===
| Fonction | Version Kubernetes | Portes-fonctions requises ? 


| Trident  a| 
1,27 - 1,33
 a| 
Non



| Snapshots de volume  a| 
1,27 - 1,33
 a| 
Non



| Volume persistant à partir des copies Snapshot des volumes  a| 
1,27 - 1,33
 a| 
Non



| Redimensionnement PV iSCSI  a| 
1,27 - 1,33
 a| 
Non



| Chap bidirectionnel ONTAP  a| 
1,27 - 1,33
 a| 
Non



| Règles d'exportation dynamiques  a| 
1,27 - 1,33
 a| 
Non



| Opérateur Trident  a| 
1,27 - 1,33
 a| 
Non



| Topologie CSI  a| 
1,27 - 1,33
 a| 
Non

|===


== Systèmes d'exploitation hôtes testés

Bien que Trident ne prenne pas officiellement en charge des systèmes d'exploitation spécifiques, les éléments suivants sont connus pour fonctionner :

* Versions de Red Hat Enterprise Linux CoreOS (RHCOS) prises en charge par OpenShift Container Platform (AMD64 et ARM64)
* RHEL 8+ (AMD64 ET ARM64)
+

NOTE: NVMe/TCP requiert RHEL 9 ou version ultérieure.

* Ubuntu 22.04 ou version ultérieure (AMD64 et ARM64)
* Windows Server 2022


Par défaut, Trident s'exécute dans un conteneur et s'exécute donc sur n'importe quel travailleur Linux. Toutefois, ces derniers doivent pouvoir monter les volumes offerts par Trident à l'aide du client NFS standard ou de l'initiateur iSCSI, en fonction des systèmes back-end que vous utilisez.

Le `tridentctl` Utility s'exécute également sur l'une de ces distributions de Linux.



== Configuration de l'hôte

Tous les nœuds workers du cluster Kubernetes doivent pouvoir monter les volumes provisionnés pour vos pods. Pour préparer les nœuds worker, vous devez installer les outils NFS, iSCSI ou NVMe en fonction de votre sélection de pilotes.

link:../trident-use/worker-node-prep.html["Préparez le nœud de travail"]



== Configuration du système de stockage

Trident peut nécessiter des modifications d'un système de stockage avant qu'une configuration back-end ne puisse l'utiliser.

link:../trident-use/backends.html["Configuration des systèmes back-end"]



== Ports Trident

Trident requiert l'accès à des ports spécifiques pour la communication.

link:../trident-reference/ports.html["Ports Trident"]



== Images de conteneur et versions Kubernetes correspondantes

Pour les installations à air comprimé, la liste suivante est une référence aux images de conteneur nécessaires à l'installation de Trident. Utiliser `tridentctl images` la commande pour vérifier la liste des images de conteneur nécessaires.

[cols="2"]
|===
| Versions de Kubernetes | Image de conteneur 


| v1.27.0, v1.28.0, v1.29.0, v1.30.0, v1.31.0, v1.32.0, v1.33.0  a| 
* docker.io/netapp/trident : 25.06.0
* docker.io/netapp/trident-autosupport:25.06
* registry.k8s.io/sig-storage/csi-provisionneur:v5.2.0
* registry.k8s.io/sig-storage/csi-attacher:v4.8.1
* registry.k8s.io/sig-storage/csi-resizer:v1.13.2
* registry.k8s.io/sig-storage/csi-snapshotter:v8.2.1
* registry.k8s.io/sig-storage/csi-node-driver-registratr:v2.13.0
* docker.io/netapp/trident-operator:25.06.0 (en option)


|===