---
sidebar: sidebar 
permalink: trident-concepts/snapshots.html 
keywords: provisioning, Trident 
summary: Découvrez comment Trident gère la création de snapshots de volumes pour ses pilotes. 
---
= Snapshots de volume
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez comment Trident gère la création de snapshots de volumes pour ses pilotes.



== En savoir plus sur la création de snapshots de volume

* Pour le `ontap-nas` , `ontap-san` , `gcp-cvs` , et `azure-netapp-files` pilotes, chaque volume persistant (PV) est mappé à un FlexVol volume. Par conséquent, les instantanés de volume sont créés en tant qu'instantanés NetApp . La technologie de snapshots de NetApp offre une stabilité, une évolutivité, une capacité de récupération et des performances supérieures aux technologies de snapshots concurrentes. Ces copies instantanées sont extrêmement efficaces, tant en termes de temps de création que d'espace de stockage.
* Pour le `ontap-nas-flexgroup` Chaque pilote de volume persistant est mappé à un FlexGroup. Par conséquent, des snapshots de volume sont créés sous forme de snapshots NetApp FlexGroup. La technologie Snapshot de NetApp offre davantage de stabilité, d'évolutivité, de capacité de restauration et de performances que les technologies Snapshot concurrentes. Ces copies Snapshot sont extrêmement efficaces, aussi bien en termes de temps de création que d'espace de stockage.
* Pour le `ontap-san-economy` pilote, les volumes persistants sont mappés aux LUN créées sur des volumes FlexVol partagés. Les volumes Volumesnapshots des volumes persistants sont atteints en exécutant des copies FlexClone de la LUN associée. Grâce à la technologie FlexClone de ONTAP, il est possible de créer quasi instantanément des copies des jeux de données les plus volumineux, même les plus volumineux. Les copies partagent les blocs de données avec leurs parents. Aucun stockage n'est nécessaire, sauf pour les métadonnées.
* Pour le `solidfire-san` Pilote, chaque volume persistant est mappé sur une LUN créée dans le cluster NetApp Element/NetApp HCI. Les copies Snapshot VolumeCas sont représentées par des copies Snapshot Element de la LUN sous-jacente. Ces snapshots sont des copies à un point dans le temps et ne prennent en charge qu'une petite quantité de ressources et d'espace système.
* Lorsque vous travaillez avec les `ontap-nas` pilotes et `ontap-san`, les snapshots ONTAP sont des copies instantanées de la FlexVol et consomment de l'espace sur la FlexVol elle-même. Cela peut entraîner la quantité d'espace inscriptible dans le volume pour une réduction du temps lors de la création ou de la planification des snapshots. L'une des façons simples de résoudre ce problème est d'augmenter le volume en le redimensionnant via Kubernetes. Une autre option consiste à supprimer les snapshots qui ne sont plus nécessaires. Lorsqu'un volume Snapshot créé via Kubernetes est supprimé, Trident supprime le snapshot ONTAP associé. Les snapshots ONTAP qui n'ont pas été créés par Kubernetes peuvent également être supprimés.


Avec Trident, vous pouvez utiliser VolumeSnapshots pour créer de nouveaux PV à partir de ceux-ci. La création de volumes persistants à partir de ces instantanés est réalisée à l'aide de la technologie FlexClone pour les systèmes backend ONTAP et CVS pris en charge. Lors de la création d'un PV à partir d'un instantané, le volume de support est un FlexClone du volume parent de l'instantané. Le `solidfire-san` Le pilote utilise les clones de volumes logiciels Element pour créer des PV à partir d'instantanés. Ici, il crée un clone à partir de l'instantané de l'élément.
