---
sidebar: sidebar 
permalink: trident-protect/trident-protect-upgrade.html 
keywords: trident, protect, netapp, upgrade, new, version 
summary: Vous pouvez mettre à niveau Trident Protect vers la dernière version pour bénéficier de nouvelles fonctionnalités ou de nouveaux correctifs. 
---
= Mettez à niveau Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez mettre à niveau Trident Protect vers la dernière version pour bénéficier de nouvelles fonctionnalités ou de nouveaux correctifs.

[NOTE]
====
Lors d'une mise à niveau depuis la version 24.10, les snapshots exécutés pendant la mise à niveau peuvent échouer. Cet échec n'empêche pas la création de futurs snapshots, qu'ils soient manuels ou planifiés. Si un snapshot échoue pendant la mise à niveau, vous pouvez en créer un manuellement pour garantir la protection de votre application.

Pour éviter d'éventuels échecs, vous pouvez désactiver toutes les planifications d'instantanés avant la mise à niveau et les réactiver ensuite. Cependant, cela entraînera l'absence d'instantanés planifiés pendant la période de mise à niveau.

====
Pour mettre à niveau Trident Protect, procédez comme suit.

.Étapes
. Mettez à jour le référentiel Trident Helm :
+
[source, console]
----
helm repo update
----
. Mettez à niveau les CRD Trident Protect :
+

NOTE: Cette étape est requise si vous effectuez une mise à niveau à partir d'une version antérieure à 25.06, car les CRD sont désormais inclus dans le tableau de protection du casque Trident.

+
.. Exécutez cette commande pour déplacer la gestion des CRD de  `trident-protect-crds` à  `trident-protect` :
+
[source, console]
----
kubectl get crd | grep protect.trident.netapp.io | awk '{print $1}' | xargs -I {} kubectl patch crd {} --type merge -p '{"metadata":{"annotations":{"meta.helm.sh/release-name": "trident-protect"}}}'
----
.. Exécutez cette commande pour supprimer le secret Helm pour le  `trident-protect-crds` graphique:
+

NOTE: Ne désinstallez pas le  `trident-protect-crds` graphique à l'aide de Helm, car cela pourrait supprimer vos CRD et toutes les données associées.

+
[source, console]
----
kubectl delete secret -n trident-protect -l name=trident-protect-crds,owner=helm
----


. Mise à niveau de Trident Protect :
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect --version 100.2506.0 --namespace trident-protect
----

