---
sidebar: sidebar 
permalink: trident-protect/trident-protect-installation.html 
keywords: install, trident, protect, requirements, registry 
summary: Si votre environnement répond aux exigences requises, vous pouvez suivre ces étapes pour installer Trident Protect. 
---
= Installer et configurer Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si votre environnement satisfait aux exigences de Trident Protect, vous pouvez suivre ces étapes pour installer Trident Protect sur votre cluster. Vous pouvez obtenir Trident Protect de NetApp ou l'installer à partir de votre propre registre privé. L'installation à partir d'un registre privé est utile si votre cluster ne peut pas accéder à Internet.



== Installez Trident Protect

[role="tabbed-block"]
====
.Installez Trident Protect from NetApp
--
.Étapes
. Ajout du référentiel Trident Helm :
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. Utilisez Helm pour installer Trident Protect. Remplacer `<name-of-cluster>` par un nom de cluster, qui sera attribué au cluster et utilisé pour identifier les sauvegardes et snapshots du cluster :
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --version 100.2506.0 --create-namespace --namespace trident-protect
----


--
.Installez Trident Protect à partir d'un registre privé
--
Vous pouvez installer Trident Protect à partir d'un registre d'images privé si votre cluster Kubernetes ne peut pas accéder à Internet. Dans ces exemples, remplacez les valeurs entre parenthèses par les informations de votre environnement :

.Étapes
. Extrayez les images suivantes sur votre ordinateur local, mettez à jour les balises, puis envoyez-les vers votre registre privé :
+
[source, console]
----
docker.io/netapp/controller:25.06.0
docker.io/netapp/restic:25.06.0
docker.io/netapp/kopia:25.06.0
docker.io/netapp/kopiablockrestore:25.06.0
docker.io/netapp/trident-autosupport:25.06.0
docker.io/netapp/exechook:25.06.0
docker.io/netapp/resourcebackup:25.06.0
docker.io/netapp/resourcerestore:25.06.0
docker.io/netapp/resourcedelete:25.06.0
docker.io/bitnami/kubectl:1.30.2
gcr.io/kubebuilder/kube-rbac-proxy:v0.16.0
----
+
Par exemple :

+
[source, console]
----
docker pull docker.io/netapp/controller:25.06.0
----
+
[source, console]
----
docker tag docker.io/netapp/controller:25.06.0 <private-registry-url>/controller:25.06.0
----
+
[source, console]
----
docker push <private-registry-url>/controller:25.06.0
----
+

NOTE: Pour obtenir la carte de barre, commencez par la télécharger sur un ordinateur connecté à Internet. `helm pull trident-protect --version 100.2506.0 --repo https://netapp.github.io/trident-protect-helm-chart`, puis copiez le résultat `trident-protect-100.2506.0.tgz` Téléchargez le fichier dans votre environnement hors ligne et installez-le en utilisant `helm install trident-protect ./trident-protect-100.2506.0.tgz` au lieu de la référence au dépôt dans l'étape finale.

. Créer l'espace de noms du système Trident Protect :
+
[source, console]
----
kubectl create ns trident-protect
----
. Connectez-vous au registre :
+
[source, console]
----
helm registry login <private-registry-url> -u <account-id> -p <api-token>
----
. Créez un secret Pull à utiliser pour l'authentification de registre privé :
+
[source, console]
----
kubectl create secret docker-registry regcred --docker-username=<registry-username> --docker-password=<api-token> -n trident-protect --docker-server=<private-registry-url>
----
. Ajout du référentiel Trident Helm :
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. Créez un fichier nommé `protectValues.yaml`. Assurez-vous qu'il contient les paramètres Trident Protect suivants :
+
[source, yaml]
----
---
controller:
  image:
    registry: <private-registry-url>
rbacProxy:
  image:
    registry: <private-registry-url>
crCleanup:
  imagePullSecrets:
    - name: regcred
webhooksCleanup:
  imagePullSecrets:
    - name: regcred
----
+

NOTE: Le `controller.image.registry` Ce paramètre s'applique à toutes les images des composants, y compris `resourcebackup` et `resourcerestore`. Si vous envoyez des images vers un chemin de dépôt spécifique au sein de votre registre (par exemple, `example.com:443/my-repo`), veuillez inclure le chemin complet dans le champ d'enregistrement. Cela permettra de garantir que toutes les images sont extraites de `<private-registry-url>/<image-name>:<tag>`.

. Utilisez Helm pour installer Trident Protect. Remplacer `<name_of_cluster>` par un nom de cluster, qui sera attribué au cluster et utilisé pour identifier les sauvegardes et snapshots du cluster :
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name_of_cluster> --version 100.2506.0 --create-namespace --namespace trident-protect -f protectValues.yaml
----


--
====

NOTE: Pour plus d'options de configuration des graphiques Helm, notamment les paramètres AutoSupport et le filtrage des espaces de noms, veuillez consulter la documentation. link:trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["Personnaliser l'installation de Trident Protect"].
